### ISSUE TITLE
[RPC] Split signrawtransaction into multiple distinct RPCs

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#10570]
The current signrawtransaction rpc command is kind of a mess. It contains both wallet code and non-wallet code as well as an undocumented feature to combine multiple transactions. This issue is to track progress on this and to get some commentary on this split.

The goal of this is to result in the following (and probably in this order):
- [x] Split combination of transactions into a new RPC that also handles the combination (#10571)
- [x] Split `signrawtransaction` into wallet and non-wallet RPCs. (#10579)
- [x] Mark `signrawtransaction` as deprecated (#10579)
- [x] Remove `signrawtransaction` (#12490)

**Comment by sipa** [comment]
One idea would be to combine this with a new partial transaction format (using header byte 0xff rather than 0x00?), which can contain redundant information:
* The UTXOs being spent (so that the signer doesn't need access to the UTXO set)
* The redeemscript in case of P2SH/witness outputs.
* Which output(s) to send change to (before it's known how much that change will be).
* ...

**Comment by achow101** [comment]
@sipa that would be out of scope for this. Such a format could be added later. This issue is really only for the cleanup of the mess that is `signrawtransaction`

**Comment by achow101** [comment]
Closing now that #12490 has been merged
