### ISSUE TITLE
Retire the comparison test framework

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#10603]
The comparison test framework was introduced in #5981 as a successor to the Java comparison tool, following discussion in #4545. The Java comparison tool was finally removed in #8504.

The python comparison test framework was originally intended to start multiple bitcoind nodes on different versions, send various blocks/transactions to those nodes, and compare that the nodes reach the same state. However, the tests are now usually run through the test_runner.py framework with only one node being run. The comparison part of the comparison test framework is not even used.

Tests written in the 'comparison' style make use of `TestManager` and `TestInstance` classes and yield statements throughout the test. The framework is overly complex and not flexible enough to be really useful. In addition, they're difficult to write, understand, update and troubleshoot. There are only 7 tests which use the comparison test style - we should rewrite them in the regular BitcoinTestFramework style.

## subtasks

- [x] Convert bip65-cltv-p2p.py to use the BitcoinTestFramework (#10695)
- [x] Convert bipdersig-p2p.py to use the BitcoinTestFramework (#10695)
- [x] Convert invalidtxrequest.py to use the BitcoinTestFramework (#11771)
- [x] Convert p2p_invalid_block.py to use the BitcoinTestFramework (#11772)
- [x] Convert feature_block.py to use the BitcoinTestFramework (#11773)
- [x] Convert feature_csv_activation.py to use the BitcoinTestFramework (#11817)
- [x] Delete redundant feature_bip9_softforks.py (#11818)
- [x] Remove the ComparisonTestFramework code (#11818)

**Comment by jnewbery** [comment]
The tests that use the comparison test framework are:

- bip65-cltv-p2p.py
- bip68-112-113-p2p.py
- bip9-softforks.py
- bipdersig-p2p.py
- invalidblockrequest.py
- invalidtxrequest.py
- p2p-fullblocktest.py

**Comment by jli225** [comment]
This repository has been hijacked by Wladimir J. van der Laan and his Blockstream ally.

If you want to contribute to Bitcoin, please come to github.com/btc1/bitcoin

**Comment by MarcoFalke** [comment]
I'd be surprised if our tests run with a version of bitcoind older than a couple of weeks. Usually our test framework is using all "bleeding edge" features of the master branch and breaks if those features are not included in the binary. E.g. the binary of the last release.

We would probably need to enforce compatibility, i.e. run the comparison tests as part of travis.

**Comment by TheBlueMatt** [comment]
It would be nice for the test to support running against an old bitcoind, but I see no reason why it should need to run multiple bitcoinds at once (we already support providing a path to a bitcoind, or, obviously, you can just leave an old binary in the tree).

**Comment by jnewbery** [comment]
#11773 merged. Next at bat: #11817.

**Comment by jnewbery** [comment]
https://github.com/bitcoin/bitcoin/pull/11817 is merged. Next up: #11818

**Comment by fanquake** [comment]
Closing now that #11818 is merged.

**Comment by jnewbery** [comment]
You're too fast @fanquake - I was looking forward to closing this myself :cry:

**Comment by jnewbery** [comment]
That's better

**Comment by MarcoFalke** [comment]
:ok_hand:
