### ISSUE TITLE
Dynamic wallet load / create / unload

### ISSUE THREAD

**Issue by jnewbery** [bitcoin/bitcoin#13059]
This meta-issue tracks the actions required to have full wallet load/create/unload at runtime.

- [x] Add locking to the global `vpwallets` to ensure no concurrency races when adding to the vector. This is sufficient thread safety for `loadwallet` and `createwallet`, but not `unloadwallet` (#13017 and #13028).
- [x] Add `loadwallet` RPC. Initially, this won't update the available wallets in the GUI (#10740)
- [x] Hook up the `loadwallet` RPC to `CClientUIInterface::LoadWallet()` so newly loaded wallets are available in the GUI (#13097)
- [x] Add `createwallet` RPC. Initially, this won't update the available wallets in the GUI (#13058)
- [x] Update `vpwallets` to be shared pointers (or similar) so that wallets can be freed safely (#13063).
- [x] Add `unloadwallet` RPC. Initially, this won't update the available wallets in the GUI (#13111)
- [x] Hook up the `unloadwallet` RPC to a new `CClientUIInterface::UnloadWallet()` function so unloaded wallets are removed from the GUI (#13111)
- [ ] Add an "open wallet" command in bitcoin-qt (#15153 and #15204)
- [x] Add a "close wallet" command in bitcoin-qt (#15195)
- [x] Add a "create wallet" command in bitcoin-qt (#15450)

**Comment by jnewbery** [comment]
#13111 is merged.

Final task is to add GUI menu items to open/close/create wallets. "Open wallet" is covered by #13100. @promag - what do you think about extending that PR to also cover closing/creating wallets?

**Comment by promag** [comment]
@jnewbery thought the same!

**Comment by jnewbery** [comment]
There's a bug in the loadwallet implementation: #13552

**Comment by promag** [comment]
@jnewbery 

> Add an "unload wallet" command in bitcoin-qt so wallets can be unloaded in the GUI (no PR yet)

Done in #13100.

**Comment by MeshCollider** [comment]
#15153 has been merged (open menu)

**Comment by jnewbery** [comment]
#15195 merged \o/

**Comment by fanquake** [comment]
#15450 has been merged (create wallet).

**Comment by Sjors** [comment]
We should probably expand the scope with QT remembering which wallets were open in the previous session. E.g. #11082

**Comment by jnewbery** [comment]
> We should probably expand the scope

Let's keep this issue tracking the basic functionality of open/close/create wallets over RPC and in the GUI. Persisting which wallets are open in the GUI is a nice enhancement, but not a basic requirement.

**Comment by MarcoFalke** [comment]
This has missed the deadline in #15940

**Comment by promag** [comment]
I guess this can be closed after #15204.

**Comment by Sjors** [comment]
I think we close this now; that last ticket can stand on its own.

**Comment by promag** [comment]
Sure.
