### ISSUE TITLE
Meta-issue: Add Clang thread safety analysis annotations

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#13129]
This meta-issue tracks the status of the Clang thread safety analysis PRs.

- [x] Fix `-Wthread-safety-analysis` warnings. Compile with `-Wthread-safety-analysis` if available. (#10866)
- [x] travis: Build with `--enable-werror` under OS X (#10923)
- [x] net: Add missing lock in `ProcessHeadersMessage(...)` (#11578)
- [x] addrman: Add missing lock in `Clear()` (CAddrMan) (#11585)
- [x] rpc: Lock `cs_main` in `blockToJSON`/`blockheaderToJSON` (#11618)
- [x] Avoid lock: Call `FlushStateToDisk(...)` regardless of `fCheckForPruning` (#11617)
- [x] tests: Add missing locks to tests (#11623)
- [x] Add missing `cs_wallet`/`cs_KeyStore` locks to wallet (#11634)
- [ ] Add missing locks: `validation.cpp` + related (#11652)
- [x] mempool: Fix missing locking in `CTxMemPool::check(…)` and `CTxMemPool::setSanityCheck(…)` (#11689)
- [x] qt: Remove redundant locks (#11733)
- [x] net: Add missing locks in `net.{cpp,h}` (#11744)
- [x] Avoid locking mutexes that are already held by the same thread (#11762)
- [x] net: Avoid locking `cs_vNodes` twice when calling `FindNode(...)`. Add `NodeExists(...)` (#11795)
- [x] tests: Make `test_bitcoin` pass under ThreadSanitzer (`clang`). Fix lock-order-inversion (potential deadlock). (#12882)
- [x] Add compile time checking for all `cs_KeyStore` runtime locking assertions (#13077)
- [x] mempool: Add compile time checking for all `::mempool.cs` runtime locking assertions (#13080)
- [x] wallet: Add compile time checking for all `cs_wallet` runtime locking assertions (#13081)
- [x] Add compile time checking for all `cs_main` runtime locking assertions (#13083)
- [x] wallet/keystore: Add Clang thread safety annotations for variables guarded by `cs_KeyStore` (#13114)
- [x] addrman: Add Clang thread safety annotations for variables guarded by `cs_addrMan` (#13115)
- [x] Add Clang thread safety annotations for variables guarded by `cs_{rpcWarmup,nTimeOffset,warnings}` (#13116)
- [x] net: Add Clang thread safety annotations for guarded variables in the networking code (#13123)
- [x] scheduler: Add Clang thread safety annotations for variables guarded by `m_cs_callbacks_pending` (#13125)
- [x] util: Add Clang thread safety annotations for variables guarded by `cs_args` (#13126)
- [x] wallet: Add Clang thread safety annotations for variables guarded by `cs_db` (#13127)
- [x] policy: Add Clang thread safety annotations for variables guarded by `cs_feeEstimator` (#13128)
- [x] Move `cs_main` locking annotations from `.cpp` to `.h` (#14063)
- [x] tests: Add missing locking annotations and locks (`g_cs_orphans`) (#14108)
- [x] Add compile time checking for `cs_main` locks which we assert at run time (#14444)

**Comment by practicalswift** [comment]
Updated: #13080 has now been merged. Now at 11 of 27 PRs merged! :-)

**Comment by practicalswift** [comment]
Update: #13116 has now been merged. Now at 12 of 27 PRs merged! :-)

**Comment by practicalswift** [comment]
Update: #13125 have now been merged. Now at 16 of 27 PRs merged (59 %) :-)

**Comment by practicalswift** [comment]
Update: #13114 has now been merged. Now at 17 of 27 PRs merged (63 %) :-)

**Comment by practicalswift** [comment]
Update: #11762 has now been merged. Now at 19 of 27 PRs merged (70 %) :-)

**Comment by practicalswift** [comment]
Update: #11795 has now been closed. Now at 20 of 27 PRs merged (74 %) :-)

**Comment by practicalswift** [comment]
Update: #13083 has now been merged. Now at 22 of 27 PRs merged (81 %) :-)

**Comment by practicalswift** [comment]
Update: #13126 has now been merged. Now at 23 of 27 PRs merged (85 %) :-)

**Comment by practicalswift** [comment]
Good news!

With 22 of 27 locking annotations PRs we're only five PR:s away from 100 % :-)

These are the five remaining PRs that need review:
* #11634: "wallet: Add missing cs_wallet/cs_KeyStore locks to wallet"
* #11652: "Add missing locks: validation.cpp + related"
* #13115: "addrman: Add Clang thread safety annotations for variables guarded by cs_addrMan"
* #13123: "net: Add Clang thread safety annotations for guarded variables in the networking code"
* #13128: "policy: Add Clang thread safety annotations for variables guarded by cs_feeEstimator"

I'm reaching out to @ajtowns @laanwj @MarcoFalke @promag @TheBlueMatt - you've all reviewed/commented on one or more of these PRs previously.

If you have time - please review these five remaining PRs :-)

**Comment by MarcoFalke** [comment]
I think most of this is done. The remaining things have pull requests open.
