### ISSUE TITLE
[Chasing Feedback] guix: Tracking ticket for eventual release build transition

### ISSUE THREAD

**Issue by dongcarl** [bitcoin/bitcoin#16496]
___Last updated Nov 25th, 2019___

## Overview

With initial Guix building support having landed in #15277, we should start thinking about what features are lacking, and which ones are required for a transition of our release process to Guix.

**ATTN**: I'm actively looking for feedback on this, please don't hesitate to ask for clarification or propose changes!

## Open PR chains

#16519 <- #17595
#17099

### Prerequisites for Release Process transition

- [x] Non-Linux cross-compilation
  - [x] OS X
    - [x] x86_64-apple-darwin14
  - [x] Windows
    - [x] x86_64-w64-mingw32
- [ ] Signing and verification
- [x] Inferiors (reproducibility across time) https://github.com/bitcoin/bitcoin/pull/16519
  - [ ] Filesystem channels (Guix upstream feature)
- [ ] Guix release process documentation

### Nice-to-have's

- [ ] APT repository for Guix itself
- [ ] Finer-grain documentation of compiler/glibc/linux-header versions
- [ ] `guix environment` as a single-command development setup tool
- [ ] Guix importer for depends syntax
- [ ] Backup plan for releases if all depends download sources are down

#### OS X

Our `native_cctools` package in depends assumes that the base system is Ubuntu, and downloads a binary clang. There needs to be a way to use a system-supplied clang. It seems that forks of Bitcoin Core already have that functionality, so it should be back ported: https://github.com/bitcoin/bitcoin/pull/15277#issuecomment-511026840

___`depends` PR Open Oct 10th, 2019:___ https://github.com/bitcoin/bitcoin/pull/17099

#### Windows

Porting NSIS to Guix was somewhat difficult the last time I attempted it, mostly because I don't know `scons` that well and NSIS doesn't have great compilation documentation.

___Update Aug 9th, 2019:___ https://github.com/bitcoin/bitcoin/issues/16496#issuecomment-520019284
___PR Open Nov 25th, 2019:___ https://github.com/bitcoin/bitcoin/pull/17595

### Signing and verification

I looked briefly into `signify`, but decided that we don't want to put the burden of extra key material on maintainers. Current thought is that a clear signature of the `find output/ -type f -print0 | sort -z | xargs -r0 sha256sum` might be sufficient.

### Inferiors

Work has mostly been finished on my branch here: https://github.com/bitcoin/bitcoin/compare/master...dongcarl:2019-06-guix-channels-and-inferiors ([commit-ish permalink](https://github.com/bitcoin/bitcoin/compare/master...dongcarl:8c10542c509b0c67be6bb487ff18ecb53c535c21))

I did some thorough testing of the inferiors infrastructure with this branch and found a bug, reported here: https://issues.guix.gnu.org/issue/36777

Luckily we were able to bisect where the error was introduced and lead Guix maintainers are actively helping with this issue.

___PR Open Aug 1st, 2019:___ https://github.com/bitcoin/bitcoin/pull/16519
___Resolved upstream Aug 16th, 2019:___ https://issues.guix.gnu.org/issue/36777#7

#### Filesystem channels

A Guix channel is like a debian APT repository but more powerful. Right now in my branch, we use my `bitcoin-guix` channel ([seen here](
 https://github.com/bitcoin/bitcoin/blob/8c10542c509b0c67be6bb487ff18ecb53c535c21/contrib/guix/manifest.scm#L6)) which supplies all of the bitcoin-specific toolchain packages, as [seen here](https://github.com/dongcarl/bitcoin-guix/blob/9b221d425b000975b2e0d1632658f1558b9d2e05/packages.scm).

I'd much prefer to embed this channel into the bitcoin repository, but right now Guix channels can only refer to git repositories. After asking on IRC, this seems like a feature that the other Guix maintainers want as well, so it should be implemented and used.

___Update Nov 25th, 2019___: :man_shrugging: Let's just use https://github.com/bitcoin-core/packaging

#### APT repository for Guix itself

A debian maintainer Vagrant Cascadian has done most of the heavy-lifting here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=850644, however, he warned me that it might be a while before it gets into debian proper, so we could have an APT repository for Guix to make the installation process for Guix easier.

### Finer-grain documentation of compiler/glibc/linux-header versions

Right now we are using:
```
gcc-9
glibc-2.27
linux-libre-headers-4.19
```

This can be verified [here](https://github.com/dongcarl/bitcoin-guix/blob/9b221d425b000975b2e0d1632658f1558b9d2e05/packages.scm#L90). We can now explicitly document this, as it won't change at the whim of Ubuntu developers. ([motivating example](https://github.com/bitcoin/bitcoin/pull/16370#discussion_r306447252))

### `guix environment` as a single-command development setup tool

Right now, on any machine with `guix` installed, `guix environment --manifest=contrib/guix/manifest.scm` sets up a native build environment for depends. I would like to extend this to also be able to setup a cross-build environment. And with "Guix importer for depends syntax", `guix environment --manifest=contrib/guix/manifest.scm` can even build the dependencies.

### Guix importer for depends syntax

AFAIK @nothingmuch has gotten started on this. It will allow for automatic generation of Guix package definitions of our depends packages so that we can maintain a single source of truth but get the caching/inferior/etc. benefits of native Guix packages.

**Comment by fanquake** [comment]
Concept ACK. Nice write-up of everything that's in the Guix pipeline.

> Our native_cctools package in depends assumes that the base system is Ubuntu, and downloads a binary clang. There needs to be a way to use a system-supplied clang.

I'd be happy to take a look at this once the current macOS toolchain changes are in.

**Comment by dongcarl** [comment]
I have successfully packaged `nsis` and the `x86_64-w64-mingw32` toolchain in Guix, good news for Windows target cross-compilation. :relaxed:

**Comment by MarcoFalke** [comment]
Wow, that means we can finally run the Windows installer with emojis in the path?! 

#13817 

stonks :chart_with_upwards_trend:

**Comment by sipa** [comment]
Ok but who uses that?

https://xkcd.com/619/

**Comment by dongcarl** [comment]
> Wow, that means we can finally run the Windows installer with emojis in the path?!
> 
> #13817
> 
> stonks chart_with_upwards_trend

I can confirm that I *am* building with `UNICODE=yes` :relaxed:

**Comment by fanquake** [comment]
We now have a [guix-channel](https://github.com/bitcoin-core/guix-channel) repo in the bitcoin-core org.

**Comment by MarcoFalke** [comment]
What is is for? Why can't schemes be in the main repo?

**Comment by dongcarl** [comment]
> What is is for? Why can't schemes be in the main repo?

@MarcoFalke Right now Guix channels can only be Git repos, not local directories. I might upstream something in the future that will allow it to point to local directories, but it isn't possible for now.

**Comment by rockandska** [comment]
> 
> 
> > What is is for? Why can't schemes be in the main repo?
> 
> @MarcoFalke Right now Guix channels can only be Git repos, not local directories. I might upstream something in the future that will allow it to point to local directories, but it isn't possible for now.

Not a guix expert,but is it not the purpose of env `GUIX_PACKAGE_PATH` variable ?

**Comment by MarcoFalke** [comment]
I think there is some chat about that here: https://github.com/bitcoin/bitcoin/pull/16519#issuecomment-531751329

**Comment by laanwj** [comment]
I've created a project for the guix transition: https://github.com/bitcoin/bitcoin/projects/13

**Comment by dongcarl** [comment]
Closing in favor of #21145
