### ISSUE TITLE
Release process for 0.19.0

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#16996]
## Before 0.19 split-off

- [x] Update [bips.md](bips.md) to account for changes since the last release (#16997).
- [x] Update hardcoded [seeds](/contrib/seeds/README.md) (#16999).
- [x] Update `src/chainparams.cpp` (#17002)
  - [x] nMinimumChainWork with information from the getblockchaininfo rpc.
  - [x] defaultAssumeValid with information from the getblockhash rpc.
    - The selected value must not be orphaned so it may be useful to set the value two blocks back from the tip.
    - Testnet should be set some tens of thousands back from the tip due to reorgs there.
    - This update should be reviewed with a reindex-chainstate with assumevalid=0 to catch any defect that causes rejection of blocks in the past history.
  - [x] m_assumed_blockchain_size and m_assumed_chain_state_size with the current size plus some overhead (see [this](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#how-to-calculate-m_assumed_blockchain_size-and-m_assumed_chain_state_size) for information on how to calculate them).
  - [x] chainTxData with statistics about the transaction count and rate. Use the output of the RPC `getchaintxstats`, see [this pull request](https://github.com/bitcoin/bitcoin/pull/12270) for an example. Reviewers can verify the results by running `getchaintxstats <window_block_count> <window_last_block_hash>` with the `window_block_count` and `window_last_block_hash` from your output.

## After 0.19 split-off, before rc1

- [x] Collect release notes fragments, put release notes on wiki
- [x] On both the master branch and the new release branch (#17007 for master):
  - update `CLIENT_VERSION_MINOR` in [`configure.ac`](../configure.ac)
  - update `CLIENT_VERSION_MINOR`, `PACKAGE_VERSION`, and `PACKAGE_STRING` in [`build_msvc/bitcoin_config.h`](/build_msvc/bitcoin_config.h)
- [x] On the new release branch in [`configure.ac`](../configure.ac) and [`build_msvc/bitcoin_config.h`](/build_msvc/bitcoin_config.h) (see [this commit](https://github.com/bitcoin/bitcoin/commit/742f7dd)):
  - set `CLIENT_VERSION_REVISION` to `0`
  - set `CLIENT_VERSION_IS_RELEASE` to `true`
- [x] Bump gitian descriptor version on master (#17049)

## Release candidates done
- [x] rc1
- [x] rc2 (doa)
- [x] rc3

## Before every release candidate

- [ ] Update translations (ping wumpus on IRC) see [translation_process.md](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md#synchronising-translations). (rc1: https://github.com/bitcoin/bitcoin/commit/6db76c6bc7fe749d1576b69dd5742c5400a476eb)
- [ ] Update manpages, see [gen-manpages.sh](https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/README.md#gen-manpagessh). (rc1: https://github.com/bitcoin/bitcoin/commit/913972944b4f436a8afc1894352338db6b0f9561)
- [ ] Update release candidate version in `configure.ac` (`CLIENT_VERSION_RC`). (rc1: https://github.com/bitcoin/bitcoin/commit/57eb126416ff6386bf21e7fad03783acb4b0171a)

## Before -final
- [ ] Finalize release notes #17403
- [ ] Update version in `configure.ac` (don't forget to set `CLIENT_VERSION_RC` to `0`).

**Comment by fanquake** [comment]
> Collect release notes fragments, put release notes on wiki

We need to remember to address [this comment](https://github.com/bitcoin/bitcoin/pull/16690#discussion_r329287449) from @jb55.

**Comment by MarcoFalke** [comment]
@harding Have you been working on this https://github.com/bitcoin/bitcoin/pull/16690#discussion_r329287449 ?

**Comment by laanwj** [comment]
The last PRs blocking the 0.19 split-off are : #16999 #16952 #16849 #16727

**Comment by laanwj** [comment]
Release notes will be at https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.19.0-Release-Notes-Draft after the split-off (thanks @jonatack).

**Comment by MarcoFalke** [comment]
Moved release notes :rocket:

**Comment by umarajib0** [comment]
> ## Before 0.19 split-off
> * [x]  Update [bips.md](bips.md) to account for changes since the last release (#16997).
> * [x]  Update hardcoded [seeds](/contrib/seeds/README.md) (#16999).
> * [x]  Update `src/chainparams.cpp` (#17002)
>   
>   * [x]  nMinimumChainWork with information from the getblockchaininfo rpc.
>   * [x]  defaultAssumeValid with information from the getblockhash rpc.
>     
>     * The selected value must not be orphaned so it may be useful to set the value two blocks back from the tip.
>     * Testnet should be set some tens of thousands back from the tip due to reorgs there.
>     * This update should be reviewed with a reindex-chainstate with assumevalid=0 to catch any defect that causes rejection of blocks in the past history.
>   * [x]  m_assumed_blockchain_size and m_assumed_chain_state_size with the current size plus some overhead (see [this](https://github.com/bitcoin/bitcoin/blob/master/doc/release-process.md#how-to-calculate-m_assumed_blockchain_size-and-m_assumed_chain_state_size) for information on how to calculate them).
>   * [x]  chainTxData with statistics about the transaction count and rate. Use the output of the RPC `getchaintxstats`, see [this pull request](https://github.com/bitcoin/bitcoin/pull/12270) for an example. Reviewers can verify the results by running `getchaintxstats <window_block_count> <window_last_block_hash>` with the `window_block_count` and `window_last_block_hash` from your output.
> 
> ## After 0.19 split-off, before rc1
> * [x]  Collect release notes fragments, put release notes on wiki
> * [x]  On both the master branch and the new release branch (#17007 for master):
>   
>   * update `CLIENT_VERSION_MINOR` in [`configure.ac`](../configure.ac)
>   * update `CLIENT_VERSION_MINOR`, `PACKAGE_VERSION`, and `PACKAGE_STRING` in [`build_msvc/bitcoin_config.h`](/build_msvc/bitcoin_config.h)
> * [x]  On the new release branch in [`configure.ac`](../configure.ac) and [`build_msvc/bitcoin_config.h`](/build_msvc/bitcoin_config.h) (see [this commit](https://github.com/bitcoin/bitcoin/commit/742f7dd)):
>   
>   * set `CLIENT_VERSION_REVISION` to `0`
>   * set `CLIENT_VERSION_IS_RELEASE` to `true`
> * [x]  Bump gitian descriptor version on master (#17049)
> 
> ## Release candidates done
> * [x]  rc1
> 
> ## Before every release candidate
> * [ ]  Update translations (ping wumpus on IRC) see [translation_process.md](https://github.com/bitcoin/bitcoin/blob/master/doc/translation_process.md#synchronising-translations). (rc1: [6db76c6](https://github.com/bitcoin/bitcoin/commit/6db76c6bc7fe749d1576b69dd5742c5400a476eb))
> * [ ]  Update manpages, see [gen-manpages.sh](https://github.com/bitcoin/bitcoin/blob/master/contrib/devtools/README.md#gen-manpagessh). (rc1: [9139729](https://github.com/bitcoin/bitcoin/commit/913972944b4f436a8afc1894352338db6b0f9561))
> * [ ]  Update release candidate version in `configure.ac` (`CLIENT_VERSION_RC`). (rc1: [57eb126](https://github.com/bitcoin/bitcoin/commit/57eb126416ff6386bf21e7fad03783acb4b0171a))
> 
> ## Before -final
> * [ ]  Finalize release notes
> * [ ]  Update version in `configure.ac` (don't forget to set `CLIENT_VERSION_RC` to `0`).

**Comment by MarcoFalke** [comment]
Anyone want to fix this: https://github.com/bitcoin/bitcoin/pull/16957#issuecomment-536713463 ?

**Comment by laanwj** [comment]
I found it very hard to describe the change. Something like:?

> The chainstate takes about 9% less memory, at the same time making `-dbcache` accounting more accurate (it was underestimating the use of memory before). This has the effect that `-dbcache` can be increased from say, 450 in previous versions to 500 in this versions with the same real memory use, but have more cache available for increased performance.

**Comment by harding** [comment]
I added a line to the draft notes in the wiki partly based on @laanwj's text above: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.19.0-Release-Notes-Draft/_compare/afe4767a0b9d867f376f487ad4fff2a180b50d7b...3123059fc822840ace61c24129a4291b93c7aa60

**Comment by laanwj** [comment]
@harding LGTM, thanks!

**Comment by MarcoFalke** [comment]
Anything left to do for the release or is it good to go?

**Comment by laanwj** [comment]
I don't think so, maybe we should discuss in the meeting tomorrow.
