### ISSUE TITLE
build: various build system improvements

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#17768]
Opening to keep track of some of the things I'm working on at the moment. Anyone who's interested in helping out/wants to comment can do so:

- [x] Improve link time error checking using `--fatal-warnings`. Add to invocations of `AX_CHECK_LINK_FLAG`. Being done in #17874.
- [x] Add macOS binary checking to `security-check.py`. Check for `PIE`, `NOUNDEFS`. Done in #17787.
- [x] Patch our depends `ld64` to actually insert `BINDATLOAD`. The patch has been done (also Cory). Needs to be properly tested and PR'd. Add `BINDATLOAD` check to `security-check.py` at the same time.
- [x] Add macOS dynamic library checking to `symbol-check.py`. I've got a version of this [here](https://github.com/fanquake/core-review/blob/master/macos_dylib_check.py). Done in #17863.
- [ ] Add `macos_min_version` to our ld flags. This isn't so straight forward, our depends ld64 accepts `macosx_min_version` instead of `macos_min_version` and Apple hasn't yet open sourced the version of cctools in which the switchover occurred . Instead of integrating into configure, should be added to depends (this argument actually gets added to the link flags on macOS, with min version set to the OS version). Should be done on top of the ld64 changes in #16392.

I realise all of the above is macOS specific, so most may not care, however there are some non-macOS build system changes in the pipeline as well:

- [x] Test using pkg-config for `mingw-w64` Windows cross-compiles. If this works (or can be made to work) correctly, it'll eliminate the non pkg-config paths from the build system. Boost likely to be a sticking point here. Will elimiate the need for PRs like #17740.
- [x] Now that we require `glibc` >= `2.17`, we can look at eliminating some of our `memcpy`/`memmove` back-compat code.
- [x] `librt` back-compat changes done in #17738.
- [x] Qt 5.12.6 in depends. I have a branch with the changes started [here](https://github.com/fanquake/bitcoin/tree/qt_5_12_6). It doesn't yet work for various reasons. One being that you can't actually compile qt 5.12.6 for macOS targeting C++11 (even though it's a configure option), as they have started using C++14 features in the macOS portions of the code, i.e `qcocoabackingstore`. Qt have also removed `xkbcommon` from their third-party tree, which means we'll likely have to integrate it into depends. Windows wants to link against the Remote Desktop API to fix a clipboard copying bug.. . Probably something we can either patch out/turn off.

**Comment by hebasto** [comment]
> - [ ] Qt 5.12.6 in depends. I have a branch with the changes started [here](https://github.com/fanquake/bitcoin/tree/qt_5_12_6). It doesn't yet work for various reasons. One being that you can't actually compile qt 5.12.6 for macOS targeting C++11 (even though it's a configure option), as they have started using C++14 features in the macOS portions of the code, i.e `qcocoabackingstore`. Qt have also removed `xkbcommon` from their third-party tree, which means we'll likely have to integrate it into depends. Windows wants to link against the Remote Desktop API to fix a clipboard copying bug.. . Probably something we can either patch out/turn off.

There is a related [QTBUG-77310](https://bugreports.qt.io/browse/QTBUG-77310):
> Building Qt requires C+11, at a minimum, but in practice we use later features, usually under a feature define, or with a fallback of some kind. On platforms that support > C11, we've (apparently) not considered the fallback necessary, under the assumption C+14 is always available.

**Comment by hebasto** [comment]
> - [ ] Test using pkg-config for `mingw-w64` Windows cross-compiles. If this works (or can be made to work) correctly, it'll eliminate the non pkg-config paths from the build system. Boost likely to be a sticking point here. Will elimiate the need for PRs like #17740.

See: #18297

**Comment by hebasto** [comment]
@fanquake 
> - [ ] Test using pkg-config for `mingw-w64` Windows cross-compiles. If this works (or can be made to work) correctly, it'll eliminate the non pkg-config paths from the build system. Boost likely to be a sticking point here. Will elimiate the need for PRs like #17740.

Could be checked now? :)

**Comment by fanquake** [comment]
> Could be checked now? :)

👍

**Comment by fanquake** [comment]
Now that #21405 and  #21376 are merged, this can be closed.
