### ISSUE TITLE
Tor v3 support

### ISSUE THREAD

**Issue by vasild** [bitcoin/bitcoin#18884]
Meta issue to track Tor v3 support. It needs:

* [ ] Finalize [BIP155](https://github.com/bitcoin/bips/blob/master/bip-0155.mediawiki):
  * [x] Get this merged: [#907 BIP155: include changes from followup discussions](https://github.com/bitcoin/bips/pull/907)
  * [x] Get this merged: [#967 BIP155: clarify variable integer format and change time to fixed 32 bit](https://github.com/bitcoin/bips/pull/967)
  * [x] Decide how to signal for `addrv2` support - protocol version bump (as in the BIP), service bit or a new p2p message (as in the WIP implementation). Integrate that decision into the BIP (either via the above PR or separately). Done: https://github.com/bitcoin/bips/pull/907#issuecomment-641145777
  * [ ] If nothing more, flip the BIP from `Status: Draft` to `Status: Final`
* [ ] Implement BIP155
  * [x] Rebase [pull#16748 [WIP] Add support for addrv2 (BIP155)](https://github.com/bitcoin/bitcoin/pull/16748)
  * [x] Get all unit tests to pass (pull#16748)
  * [x] Get all functional tests to pass (if they don't) (pull#16748)
  * [x] Address review suggestions (pull#16748)
  * [x] Create a new PR from above (ready for review). Done: [pull#19031 Implement ADDRv2 support (part of BIP155)](https://github.com/bitcoin/bitcoin/pull/19031)
  * [x] Split [pull#19031](https://github.com/bitcoin/bitcoin/pull/19031) in smaller, digestible PRs, targeting each one to have 100% code coverage of modified code (see details on the PR page):
    * [x] Preparation changes
    * [x] Change `CNetAddr::ip` to have flexible size
    * [x] Implement `addrv2` (un)serializing
    * [x] Advertise support for `addrv2` and start sending such messages to peers
  * [ ] Document `addrv2` next to [addr](https://developer.bitcoin.org/reference/p2p_networking.html#addr)
* [x] Implement Tor v3 on top of that (#19954).

Related:
[issue#2091 Binding to multiple anonymous networks (esp. I2P)](https://github.com/bitcoin/bitcoin/issues/2091)
[issue#9214 ensure ADD_ONION implementation is compatible with upstream changes, next generation onion addresses](https://github.com/bitcoin/bitcoin/issues/9214)
[issue#18254 setting externalip=<version 3 onion address> results in error](https://github.com/bitcoin/bitcoin/issues/18254)

**Comment by vasild** [comment]
From [#bitcoin-core-dev](http://www.erisian.com.au/bitcoin-core-dev/log-2020-07-03.html#l-306):

> 19:05 < dongcarl> According to the tor-dev mailing list, Tor plans to deprecate v2 with 0.4.4.x (Sept. 15th, 2020) and obsolete it in 0.4.6.x (July 15th, 2021)
> 19:05 < dongcarl> More details here: https://lists.torproject.org/pipermail/tor-dev/2020-June/014365.html

https://github.com/bitcoin/bitcoin/pull/19031 (or https://github.com/bitcoin/bitcoin/pull/19360) would benefit from some more code review.

cc @laanwj @MarcoFalke @dongcarl @naumenkogs @TheBlueMatt

**Comment by MarcoFalke** [comment]
Can be closed, as the doc updates regard other repositories?

**Comment by vasild** [comment]
Indeed
