### ISSUE TITLE
Proposed Timeline for Legacy Wallet and BDB removal

### ISSUE THREAD

**Issue by achow101** [bitcoin/bitcoin#20160]
What to review next: #31378

***

Here is a proposed timeline for the move from legacy wallets to descriptor wallets, and at the same time, bdb to sqlite, culminating with the removal of both legacy wallets and bdb. Even though the wallet type and the wallet storage format are orthogonal to each other, as noted in #19077, I would like to tie them together for the sake of simplicity when it comes to how we make new wallets and the migration of one type to another.

The 4 combinations of type and format are: legacy-bdb, legacy-sqlite, descriptor-bdb, and descriptor-sqlite. While all 4 types will be supported, we will primarily deal with legacy-bdb and descriptor-sqlite. Setting `descriptors=True` in `createwallet` (or checking the Descriptors option in the GUI) will always make a descriptor-sqlite. Setting that to `False` will always make a legacy-bdb.

- [x] 0.21 (late 2020)
  - [x] Initial release of descriptor type and sqlite format. (#16528, #19077)
  - [x] Descriptor type is experimental with a warning as such (#16528)
  - [x] Only legacy-bdb and descriptor-sqlite will be created (#19077)
- [x] 22.0 (mid 2021)
  - [x] Implement descriptor exports (#20226)
  - [x] Legacy type remains default (no pr needed)
  - [x] Introduce `dump` and `createfromdump` wallet tool commands with an additional `-format` option to specify the wallet type (#19137)
    * Users may use `dump` and then `createfromdump` in order to make legacy-sqlite from legacy-bdb
    * Users may use `dump` and then `createfromdump` in order to make descriptor-bdb from descriptor-sqlite
  - [x] If a wallet specified in conf or command line doesn't exist, don't make a wallet and instead warn (#15454)
- [x] 23.0 (early 2022)
  - [x] Change descriptor type to non-experimental (#23002)
  - [x] Change `createwallet` `descriptors` default to `True` (#23002)
  - [x] Change wallet tool `create` `-descriptors` default to `True` (#23002)
- [x] 24.0 (late 2022)
  - [x] Introduce `migratewallet` command to migrate a legacy-bdb to descriptor-sqlite (#19602)
  - [x] For newly created legacy-bdb wallets, warn that they are deprecated and will soon be unsupported (#24505)
- [x] 26.0 (late 2023)
  - [x] When loading legacy-bdb, descriptor-bdb, or legacy-sqlite wallets, warn that the legacy type and bdb format will soon be unsupported, as applicable. (#27869)
  - [x] Deprecate creating new legacy-bdb wallets #28597 
  - [x] `migratewallet` bug fixes
    - [x] #28609
    - [x] #28546
- [x] 27.0 (early 2024)
  - [x] address book performance improvement #26836
  - [x] bulk deletion of txs performance improvement #28987
  - [x] bulk deletion of records performance improvement #29403
  - [x] Caching to improve performance of migrated non-HD descriptor wallets (also perf improvement in general) #26008
  - [x] Remove `migratewallet` experimental warning #28037 
- [x] 28.0 (late 2024)
  - [x] Improve performance of migratewallet #28574
  - [x] Reimplement legacy-bdb to descriptor-sqlite migration (maybe as a separate command or in the wallet tool) to be independent of `LegacyScriptPubKeyMan` and BDB (#26596)
  - [x] For `dump`, implement an independent BDB file loader (this should probably be shared with the previous) (#26606)
  - [x] GUI: Migrate wallets that are not loaded (https://github.com/bitcoin-core/gui/pull/824)
  - [x] Fix default wallet migration naming (#29586)
  - [x] Fix `listwalletdir` of migrated default wallets and generated backups (#30265)
- [x] 29.0 (early 2025)
  - [x] Watch-only wallet migration edge case (#31374)
  - [x] Avoid weird script corner cases (#31495)
  - [x] Rework wallet_migration.py (#31248)
  - [x] Add combinerawtransaction test that doesn't need legacy wallet (#31249)
  - [x] Remove legacy wallet from migration benchmark (#31241)
- [ ] 30.0 (late 2025)
  - [x] Remove optional sqlite when building with wallet (#31961)
  - [ ] Invalid multisigs migration edge case (#31378)
  - [x] Stop loading legacy-bdb, descriptor-bdb, legacy-sqlite wallet entirely. Inform users how to migrate (#31250)
  - [x] Remove `LegacyScriptPubKeyMan` except for the independent migration stuff (#28710)
  - [x] Remove BDB except for independent loading for migration stuff (#28710)

Additional improvements that have no target deadline:

- [x] Backwards compatibility tests fixes for descriptor wallets #28027

The migration code will probably be around for a long time/forever.

Note that we expect users who go through the effort to make a legacy-sqlite or descriptor-bdb wallet to suck it up and deal with the consequences of doing something that isn't really supported. Such users should be able to figure out for themselves how to migrate their wallets. (Maybe `migratewallet` can migrate legacy-sqlite to descriptor-sqlite. bdb to sqlite is way easier than legacy to descriptor).

**Comment by jonasschnelli** [comment]
Look good except `0.27 (late 2023)` (`Stop loading legacy-bdb [...]`).
AFAIK this would be the first time one couldn't load an historical wallet.dat file in Core (which is IMO a great feature).
Disabling the possibility of loading wallets that have been created just two years ago seems to be too strict.

Since the wallet files are precious data sources and could lead to stress when failing to load, I suggest to continue support for BDB wallets indefinitely. Support could also mean an automatic migration to sqlite with an internal dependency free converter.

**Comment by achow101** [comment]
> I suggest to continue support for BDB wallets indefinitely. Support could also mean an automatic migration to sqlite with an internal dependency free converter.

This is almost what the last step is. There will be a dependency free migration tool that users can use to move legacy-bdb wallets to descriptor-sqlite. I would be hesitant to make this automatic though.

**Comment by ChristopherA** [comment]
I'm hoping not for indefinite support of BDB wallets. It is easy enough to have an external tool do the conversion post 0.27.

**Comment by MarcoFalke** [comment]
> 0.23 Introduce migratewallet command to migrate a legacy-bdb to descriptor-sqlite

Any reason this can't be done in 22.0 already?

**Comment by achow101** [comment]
> > 0.23 Introduce migratewallet command to migrate a legacy-bdb to descriptor-sqlite
> 
> Any reason this can't be done in 22.0 already?

No, I just don't think it will make it.

**Comment by S3RK** [comment]
> 23.0 (late 2021)
> * Change `createwallet` `descriptors` default to `True`

I think it's good to add `wallet tool` here as well to not forget to change default wallet type there as well

**Comment by achow101** [comment]
Missed a few things for 23.0, so everything is going to be pushed back one release.

**Comment by luke-jr** [comment]
Concept NACK on removal. Users shouldn't be forced to upgrade their wallets (especially not on such a short timeline).

**Comment by fanquake** [comment]
Updated OP now that #24505 has been merged.

**Comment by michaelfolkson** [comment]
Concept ACK on latest updated timetable. I think it addresses @luke-jr timeline concerns and supporting the legacy wallet, BDB for the rest of Core's existence doesn't make sense to me.

**Comment by luke-jr** [comment]
2024 is very soon. Keep in mind we have literally never removed support for older wallets before.

**Comment by Sjors** [comment]
I've noticed at least two projects now that tripped over the default change for new wallets. Although it's easy to work around,  if they rely on dependencies (e.g. https://github.com/bitcoindevkit/bdk/issues/598#issuecomment-1131250261) it can get tricky. Maybe we should add a `wallet_create_legacy_default` config option (with a clear warning that it will get deprecated).

**Comment by Rspigler** [comment]
I too am concerned about how quickly we would be losing support for older wallets for the first time (less than two years from when the first warning appears about legacy/BDB being deprecated; 24.0-27.0). I think this should at least be pushed back to 28.0, but perhaps even more.

I know the PR implementing the migration isn't finished yet, but I think the warning given and the documentation around it will be very important as well.

**Comment by luke-jr** [comment]
In light of descriptor wallets not having an upgrade path for non-HD wallets, I don't think legacy wallet support can be reasonably removed.

**Comment by luke-jr** [comment]
>Why specifically do you see that as a problem?

Mainly performance issues (a SPKM for every existing key) and lack of builtin seed rotation.

But it's also a security change, which users probably shouldn't be forced into. Even hardened keys are endangered by a leaked seed.

**Comment by S3RK** [comment]
I propose to also include #26511 As part of the timeline

**Comment by michaelfolkson** [comment]
The timeline needs updating for what was left out of 24.0 and what will be included in 25.0 (obviously no rush)

**Comment by 1440000bytes** [comment]
> I find the proposed timeline in general somewhat aggressive here, and would prefer to let old wallets to just keep working for a few years longer. Historically speaking, we've never dropped support for an old wallet format, and how frequently I see reports of people trying to access old wallets, I fear this will worsen it.

Agree. Also everything doesn't work with descriptor wallets. 

Example: I have used legacy wallets in this [proof of concept](https://github.com/1440000bytes/p2p) which will be used to build a p2p exchange

**Comment by achow101** [comment]
> The timeline needs updating for what was left out of 24.0 and what will be included in 25.0 (obviously no rush)

It was updated a while ago, and should be up to date.

> Example: I have used legacy wallets in this [proof of concept](https://github.com/1440000bytes/p2p) which will be used to build a p2p exchange

There's nothing in that example that I can see that requires the use of legacy wallets. I can see why it doesn't currently work with descriptor wallets, but that's easily solved by having a watchonly wallet contain the multisig descriptor that processes the psbt first so that the multisig keys are actually included in the psbt before it goes to the signers.

**Comment by 1440000bytes** [comment]
> There's nothing in that example that I can see that requires the use of legacy wallets. I can see why it doesn't currently work with descriptor wallets, but that's easily solved by having a watchonly wallet contain the multisig descriptor that processes the psbt first so that the multisig keys are actually included in the psbt before it goes to the signers.

Sorry I do not understand this and legacy wallet UX makes it easy for buyer and seller. Please let me know if I am doing something wrong:

https://github.com/1440000bytes/p2p/issues/1

Alice has a wallet with some private keys using for some bitcoin tx
Bob has a wallet with some private keys using for some bitcoin tx

We do not want users to create another wallet to use the exchange.

**Comment by michaelfolkson** [comment]
@1440000bytes: Please ask on StackExchange or IRC. This issue is for tracking a timeline for the Core wallet, it is hard to do that if the discussion wanders off to other topics. I am already discussing this with you on the linked issue in your repo.

**Comment by 1440000bytes** [comment]
> @1440000bytes: Please ask on StackExchange or IRC. This issue is for tracking a timeline for the Core wallet, it is hard to do that if the discussion wanders off to other topics. I am already discussing this with you on the linked issue in your repo.

I was thinking about asking a question on stackexchange although I changed my mind and would instead ACK/NACK related pull requests with reasons when I need to.

Thanks for letting me know what this issue is about though.

**Comment by fanquake** [comment]
> I think the milestones will need to be edited in OP to be moved back by one release?

Moved all the remaining milestones back by a release.

**Comment by fanquake** [comment]
Now that #27869 has been merged. It might be time to no-longer mark the `migratewallet` RCP as "EXPERIMENTAL".

**Comment by fanquake** [comment]
> @fanquake Does it not need the performance fix for bdb wallets with a lot of keys first?

I'm not sure. However if we are going to ship this warning that instructs users to use `migratewallet`, I don't think we can leave it marked as experimental.

**Comment by achow101** [comment]
Seems unlikely that the bdb parser stuff will make it into 27.0, so pushed those back another release.

**Comment by Toromambo** [comment]
toromambo

**Comment by brunoerg** [comment]
fyi: https://github.com/bitcoin/bitcoin/pull/29694 (adds a fuzz target for spkm migration)

**Comment by fanquake** [comment]
Closing, given #28710 is merged.
