### ISSUE TITLE
[RFC] Splitting up rpcwallet

### ISSUE THREAD

**Issue by meshcollider** [bitcoin/bitcoin#23622]
This relates to PR #23602.

> rpcwallet is the file that takes longest to compile, especially with sanitizers enabled it can take several 10s of seconds.
>
> Allow faster incremental and parallel builds by starting to split it up. First, split off signmessage, which is unrelated to other stuff such as wallet file handling, wallet encryption, tx creation, or wallet status/info.

That PR moves `signmessage` and the `send*` RPCs to separate files in `wallet/rpc/`. I suggest we go even further with this split and do something like the following:

- [x] ~Move `wallet/rpcdump.cpp => wallet/rpc/backup.cpp` and combine with `backupwallet` and `restorewallet` RPCs.~ (Done in #23647).
- [x] ~Introduce `wallet/rpc/util.cpp` and move the helper functions there, like `GetWalletForJSONRPCRequest` and `EnsureWalletIsUnlocked`, etc.~ (Done in #23640).
- [ ] Introduce `wallet/rpc/addresses.cpp` and move `getnewaddress`, `getrawchangeaddress`, `setlabel`, `listaddressgroupings`, `addmultisigaddress`, `keypoolrefill`, `newkeypool`, `getaddressinfo`, `getaddressesbylabel`, `listlabels`, and `walletdisplayaddress` there.
- [ ] Introduce `wallet/rpc/transactions.cpp` and move `listreceivedbyaddress`, `listreceivedbylabel`, `listtransactions`, `listsinceblock`, `gettransaction`, `abandontransaction`, and `rescanblockchain` there.
- [ ] Introduce `wallet/rpc/utxos.cpp` and move `getreceivedbyaddress`, `getreceivedbylabel`, `getbalance`, `getunconfirmedbalance`, `lockunspent`, `listlockunspent`, `getbalances`, and `listunspent` there.
- [x] ~Move the `walletpassphrase`, `walletpassphrasechange`, `walletlock`, and `encryptwallet` RPCs to `wallet/rpc/encrypt.cpp`.~ (Done in #23647).
- [ ] Move the spending / signing / transaction-creation RPCs to wallet/rpc/spend.cpp.
- [ ] This would leave rpcwallet.cpp with only the `getwalletinfo`, `listwalletdir`, `listwallets`, `loadwallet`, `setwalletflag`, `createwallet`, `unloadwallet`, `sethdseed `, and `upgradewallet` RPCs, which are the "core" wallet management RPCs, so it makes sense. It could be moved to the `wallet/rpc/` directory though under a different name.

Obviously this would be a lot of movement, so it would be good to get thoughts on it first.

I'll open PRs in stages for this if there is agreement to proceed.

**Comment by MarcoFalke** [comment]
ACK. Was planning to split this mostly in the same way.

**Comment by ryanofsky** [comment]
This seems like a nice change. Few thoughts I had were

- Maybe `rpc/coins` instead of `rpc/utxos` Or maybe not. I don't know which direction usage is shifting, but "coins" always seemed more friendly and comprehensible to me.
- Maybe rename `rpcwallet` to `rpc/wallets` after all the moves, or split further into `rpc/general` `rpc/load`. In any case it would be nice to have _all_ wallet RPC methods in the `rpc/` directory.
- Personally I think this would be nicest to do in one MOVEONLY PR that did not change any existing code. That way any conflicting PR will have to be rebased at most one time, instead of possibly multiple times.

**Comment by meshcollider** [comment]
@MarcoFalke would you prefer to continue splitting it yourself? Or would you like me to implement these changes on top of #23602?

**Comment by MarcoFalke** [comment]
Shouldn't matter too much, but I think it is fine to do in multiple pull requests (first the ones without conflicts and then the ones with conflicts). For example #23602 didn't have any conflicts and I expect `util.cpp` and `encrypt.cpp` to have no conflicts either. So I'd attempt to move those next, but I won't be working on this myself for the next week, so feel free to take over in the meantime.

**Comment by meshcollider** [comment]
Alright I have moved everything as suggested in a branch on my repo, and will slowly open the moves up in stages as PRs.

**Comment by meshcollider** [comment]
@MarcoFalke is there a way to ask @DrahtBot which PRs would conflict without just opening a PR and waiting?

**Comment by MarcoFalke** [comment]
Not trivially, though the conflict detection also runs on draft pull requests and I can bump it up the scheduler queue, if needed.

**Comment by meshcollider** [comment]
Alright, I've opened a draft of the whole split just to see how many conflicts it has: #23647

**Comment by meshcollider** [comment]
All done in #23667
