### ISSUE TITLE
v23.0 testing

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#24501]
Umbrella issue for 23.0 testing. Please help testing on a wide variety of supported platforms, as well as interaction with different software.

Let us know which version you tested on which operating system.

If you find an issue, please search Github for known issues first and then open a new Github issue. This meta issue should not be used to report bugs, as a single thread makes it impossible to track more than one topic.

## What to test

For an idea what to test, see @stickies-v's [23.0 release candidate testing guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide), or

- See [Draft Release Notes](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Notes-draft) for a list of changes-
- Also see testing reports for earlier releases ([v0.21.0](https://github.com/bitcoin/bitcoin/issues/20555) [v22.0](https://github.com/bitcoin/bitcoin/issues/22634))

## Known issues (as of rc5)

Other known issues:
- MacOS: SHA256 acceleration is not enabled on MacOS 11.x due to missing reporting of sysctl `hw.optional.arm.*`. Please upgrade to MacOS 12.x if this is important to you.

## Known issues fixed (as of rc5)

- [x] ~~Due to a naming conflict after adding support for the new MacOS architecture, we had to rename the following dmgs manually from `bitcoin-23.0rc2-osx-signed.dmg` during upload:~~
```
bitcoin-23.0rc2-arm64-apple-darwin.dmg
bitcoin-23.0rc2-x86_64-apple-darwin.dmg
```
~~This may cause issues during verification because in the `SHA256SUMS.asc` they still have the old name.~~
- [x] ~~MacOS: please postpone the Monterey 12.3.1 update until 23.0rc4 to test whether #23134 has been really fixed~~ (it's really fixed, see https://github.com/bitcoin/bitcoin/issues/24501#issuecomment-1086857682)
- [x] ~~#24726 bitcoind/-qt may silently fail on Windows when using AVX2 SHA256 implementation~~
- [x] ~bitcoin-core/gui#571~~
- [x] ~~Windows GUI crashes while rendering bandwidth graph: bitcoin-core/gui#582~~

**Comment by gruve-p** [comment]
Signet miner no longer runs for me on a custom signet.

```
error code: -22
error message:
Specified sighash value does not match value stored in PSBT
Traceback (most recent call last):
  File "contrib/signet/miner", line 628, in <module>
    main()
  File "contrib/signet/miner", line 622, in main
    return args.fn(args)
  File "contrib/signet/miner", line 496, in do_generate
    psbt_signed = json.loads(args.bcli("-stdin", "walletprocesspsbt", input=psbt.encode('utf8')))
  File "contrib/signet/miner", line 603, in <lambda>
    args.bcli = lambda *a, input=b"", **kwargs: bitcoin_cli(args.cli.split(" "), list(a), input=input, **kwargs)
  File "contrib/signet/miner", line 559, in bitcoin_cli
    out = subprocess.run(cmd, stdout=subprocess.PIPE, **kwargs, check=True).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bitcoin-cli', '-signet', '-stdin', 'walletprocesspsbt']' returned non-zero exit status 22
```

When reverting PR: https://github.com/bitcoin/bitcoin/pull/22514 it works again

**Comment by Rspigler** [comment]
Compiled v23.0rc1 with default config settings in Qubes 4.0 in a Debian-11 VM with standard networking.

Passed all functional, util, and unit tests.

**Comment by hebasto** [comment]
v23.0rc2 on Windows 11:

![doc_2022-03-13_09-26-20](https://user-images.githubusercontent.com/32963518/158051492-6b2adf38-75ad-4fbf-a055-2b9864a0279b.png)

Do we really want to make a release in March with a certificate which is valid until May only?
Maybe update it?

See:
- bitcoin-core/gui#252
- bitcoin/bitcoin#22017

cc @achow101

**Comment by achow101** [comment]
@hebasto As long as the key is not revoked, there won't be any issues with the installer after it expires. Those previous issues were because the key was revoked.

**Comment by hebasto** [comment]
v23.0rc2 on macOS Monterey x86_64:

```
% shasum -a 256 bitcoin-23.0rc2-osx-signed.dmg 
8603b36da9eae23880839c1ec95c5bfb51dbec7c253095c122e3896458e78107  bitcoin-23.0rc2-osx-signed.dmg
% codesign -vvv --deep --strict bitcoin-23.0rc2-osx-signed.dmg 
bitcoin-23.0rc2-osx-signed.dmg: code object is not signed at all
```

cc @achow101

**Comment by achow101** [comment]
The dmg needs to be unpacked. The binary contained inside the dmg is signed, not the dmg itself.

**Comment by hebasto** [comment]
> The dmg needs to be unpacked. The application bundle contained inside the dmg is signed, not the dmg itself.

You're right:
```
% codesign -vvv --deep --strict /Applications/Bitcoin-Qt.app  
/Applications/Bitcoin-Qt.app: valid on disk
/Applications/Bitcoin-Qt.app: satisfies its Designated Requirement
```

**Comment by jessebarton** [comment]
Compiled v23.0rc1 FreeBSD STORAGE 13.0-RELEASE Passed all tests.

**Comment by hebasto** [comment]
Cross-posting a bug in the GUI: bitcoin-core/gui/issues/567.

**Comment by Rspigler** [comment]
I was able to fully resync the chain without issue

**Comment by hebasto** [comment]
> Cross-posting a bug in the GUI: [bitcoin-core/gui/issues/567](https://github.com/bitcoin-core/gui/issues/567).

A fix has been suggested in #24648.

**Comment by tylerchambers** [comment]
Downloaded and syncing w/ GUI on macOS 12.3 M1 with no problems so far. Great stuff!

**Comment by Ziqhoulets** [comment]
👍😉👍😎👍😊👍🤩👍😘👍
Good luck everyone
And congratulations to all stuff..
Good work..!!

**Comment by 0xB10C** [comment]
Tested the tracepoints in v23rc2 with the tests from #24358. 

```
TEST                         | STATUS    | DURATION

interface_usdt_net.py        | ✓ Passed  | 2 s
interface_usdt_utxocache.py  | ✓ Passed  | 4 s
interface_usdt_validation.py | ✓ Passed  | 1 s

ALL                          | ✓ Passed  | 7 s (accumulated)
Runtime: 4 s
```

**Comment by hebasto** [comment]
Tested https://bitcoincore.org/bin/bitcoin-core-23.0/test.rc2/bitcoin-23.0rc2-win64.zip on Windows 11 Pro 21H2.

`bitcoind.exe -signet` silently fails:
```
>bitcoind.exe -signet
2022-03-26T17:24:10Z Bitcoin Core version v23.0.0rc2 (release build)
2022-03-26T17:24:10Z Signet derived magic (message start): 0a03cf40
2022-03-26T17:24:10Z Assuming ancestors of block 00000112852484b5fe3451572368f93cfd2723279af3464e478aee35115256ef have valid signatures.
2022-03-26T17:24:10Z Setting nMinimumChainWork=000000000000000000000000000000000000000000000000000000de26b0e471
2022-03-26T17:24:10Z Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
2022-03-26T17:24:10Z Using RdSeed as additional entropy source
2022-03-26T17:24:10Z Using RdRand as an additional entropy source
2022-03-26T17:24:10Z Default data directory C:\Users\hebasto\AppData\Roaming\Bitcoin
2022-03-26T17:24:10Z Using data directory C:\Users\hebasto\AppData\Roaming\Bitcoin\signet
2022-03-26T17:24:10Z Config file: C:\Users\hebasto\AppData\Roaming\Bitcoin\bitcoin.conf
2022-03-26T17:24:10Z Command-line arg: signet=""
2022-03-26T17:24:10Z Using at most 125 automatic connections (2048 file descriptors available)
2022-03-26T17:24:10Z Using 16 MiB out of 32/2 requested for signature cache, able to store 524288 elements
2022-03-26T17:24:10Z Using 16 MiB out of 32/2 requested for script execution cache, able to store 524288 elements
2022-03-26T17:24:10Z Script verification uses 3 additional threads
2022-03-26T17:24:10Z scheduler thread start
2022-03-26T17:24:10Z HTTP: creating work queue of depth 16
2022-03-26T17:24:10Z Using random cookie authentication.
2022-03-26T17:24:10Z Generated RPC authentication cookie C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\.cookie
2022-03-26T17:24:10Z HTTP: starting 4 worker threads
2022-03-26T17:24:10Z Using wallet directory C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\wallets
2022-03-26T17:24:10Z init message: Verifying wallet(s)…
2022-03-26T17:24:10Z Using /16 prefix for IP bucketing
2022-03-26T17:24:10Z init message: Loading P2P addresses…
2022-03-26T17:24:10Z Loaded 281 addresses from peers.dat  3ms
2022-03-26T17:24:10Z init message: Loading banlist…
2022-03-26T17:24:10Z SetNetworkActive: true
2022-03-26T17:24:10Z Cache configuration:
2022-03-26T17:24:10Z * Using 2.0 MiB for block index database
2022-03-26T17:24:10Z * Using 8.0 MiB for chain state database
2022-03-26T17:24:10Z * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
2022-03-26T17:24:10Z init message: Loading block index…
2022-03-26T17:24:10Z Switching active chainstate to Chainstate [ibd] @ height -1 (null)
2022-03-26T17:24:10Z Opening LevelDB in C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\blocks\index
2022-03-26T17:24:10Z Opened LevelDB successfully
2022-03-26T17:24:10Z Using obfuscation key for C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\blocks\index: 0000000000000000
2022-03-26T17:24:10Z LoadBlockIndexDB: last block file = 2
2022-03-26T17:24:10Z LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=7157, size=116740534, heights=75849...83025, time=2022-02-03...2022-03-25)
2022-03-26T17:24:10Z Checking all blk files are present...
2022-03-26T17:24:10Z Opening LevelDB in C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\chainstate
2022-03-26T17:24:10Z Opened LevelDB successfully
2022-03-26T17:24:10Z Using obfuscation key for C:\Users\hebasto\AppData\Roaming\Bitcoin\signet\chainstate: d86c5148093b888d
2022-03-26T17:24:10Z Loaded best chain: hashBestChain=000000af126e5012ccc04cd73228deba508a60673641ec1baa412386fdfe10aa height=83025 date=2022-03-25T16:34:08Z progress=0.991581
2022-03-26T17:24:10Z init message: Verifying blocks…
2022-03-26T17:24:10Z Verifying last 6 blocks at level 3
2022-03-26T17:24:10Z [0%]...
```

**Comment by kibnakamoto** [comment]
compiled without errors but got countless warnings (hundreds) on C++17 Mac OS X.
these are a few warnings out of Hundreds:
```
/usr/local/include/boost/signals2/connection.hpp:80:22: note: overridden virtual function is here
        virtual bool connected() const = 0;
                     ^
/usr/local/include/boost/signals2/connection.hpp:195:22: warning: 'lock' overrides a member function but is not marked 'override' [-Wsuggest-override]
        virtual void lock()
                     ^
/usr/local/include/boost/signals2/connection.hpp:102:22: note: overridden virtual function is here
        virtual void lock() = 0;
                     ^
/usr/local/include/boost/signals2/connection.hpp:199:22: warning: 'unlock' overrides a member function but is not marked 'override' [-Wsuggest-override]
        virtual void unlock()
                     ^
/usr/local/include/boost/signals2/connection.hpp:103:22: note: overridden virtual function is here
        virtual void unlock() = 0;
                     ^
/usr/local/include/boost/signals2/connection.hpp:212:34: warning: 'release_slot' overrides a member function but is not marked 'override' [-Wsuggest-override]
        virtual shared_ptr<void> release_slot() const
                                 ^
/usr/local/include/boost/signals2/connection.hpp:132:34: note: overridden virtual function is here
        virtual shared_ptr<void> release_slot() const = 0;
                                 ^
31 warnings generated.
```
all the warnings are related to either the use of macros or overriding.
also got a lot of notes.

All the tests passed:
```
PASS: minisketch/test
PASS: univalue/test/object
PASS: univalue/test/unitester
PASS: univalue/test/no_nul
PASS: qt/test/test_bitcoin-qt
============================================================================
Testsuite summary for Bitcoin Core 23.99.0
============================================================================
# TOTAL: 5
# PASS:  5
# SKIP:  0
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
```

**Comment by hebasto** [comment]
@kibnakamoto 

You can use the --enable-suppress-external-warnings option when configuring your build.

**Comment by jonatack** [comment]
> You can use the --enable-suppress-external-warnings option when configuring your build.

Updated https://jonatack.github.io/articles/how-to-compile-bitcoin-core-and-run-the-tests to add the `--enable-suppress-external-warnings` flag by default (https://github.com/jonatack/jonatack.github.io/commit/e8f4c2b11ed8c6fa8791d6cdec1ed464abb66b79). I use this flag by default since it was added.

**Comment by hebasto** [comment]
> I use this flag by default since it was added.

#22041 :)

**Comment by kibnakamoto** [comment]
@hebasto
Thank you, but on the ```make deploy``` is there a library called ```ds_store``` that I should pip install to ```make deploy```?

**Comment by stickies-v** [comment]
The testing guide is now available on https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide , @laanwj could you please add that link to OP? 

If anyone has any feedback or suggested changes re the guide, please let me know!

**Comment by eriknylund** [comment]
How come there is no option to receive to `Bech32m (Taproot)` address type when the wallet is encrypted? 🤔 

This is when I create a wallet that's not encrypted:
![image](https://user-images.githubusercontent.com/20860124/160436819-1d6e6289-a2f4-4ca4-84d3-721c4ef498c6.png)
This is when I create one that is encrypted:
![image](https://user-images.githubusercontent.com/20860124/160437402-c95cf862-b814-44d8-8e9b-bd0565f30d78.png)

**Comment by eriknylund** [comment]
> The testing guide is now available on https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide , @laanwj could you please add that link to OP?
> 
> If anyone has any feedback or suggested changes re the guide, please let me know!

Thanks for a great guide! ❤️ 

For Apple M1 testers like me jumping straight at the binary, a section about how to configure for signet could be good. Otherwise, new testers might end up waiting for the IBD on mainnet. Also, if you're unfamiliar with working at the terminal, it might be intimidating at first. 

Given the .conf extension is not mapped to something obscure (like Tunnelblick in my case) these steps should work:
1. From the top menu bar, go to Bitcoin Core > Preferences... or click CMD + ,
2. Click the Open Configuration File button in the bottom left  corner and then click Continue in the next dialog.
3. The `bitcoin.conf` file will open in your file editor. Enter `signet=1` and save the file.
4. Restart Bitcoin Core. The start screen should now be yellow, and the icon in the dock should also change to yellow to indicate that you're running on Signet. You can also tell from the window title, which ends with [signet].

![image](https://user-images.githubusercontent.com/20860124/160548288-1530ea92-cc82-4383-99c5-cfb99df4155f.png)
![image](https://user-images.githubusercontent.com/20860124/160548335-037e3158-bfbe-4e6d-8184-c4250c5a4f12.png)
![image](https://user-images.githubusercontent.com/20860124/160548410-94dfdc7d-675d-42ac-ba6e-aeaa8fd15a3f.png)
![image](https://user-images.githubusercontent.com/20860124/160548475-74b4df04-506f-4821-8753-314750a3838c.png)
![image](https://user-images.githubusercontent.com/20860124/160548597-08e6665d-6914-4ae6-b23f-c5e65a40d989.png)
![image](https://user-images.githubusercontent.com/20860124/160548799-efecbcaf-e3db-40dc-ac75-05163937c36d.png)

**Comment by hebasto** [comment]
> How come there is no option to receive to `Bech32m (Taproot)` address type when the wallet is encrypted? :thinking:

Tested on Ubuntu 22.04. Confirming the bug for a just created wallet. Closing the wallet, and following re-opening it could be a temporarily workaround.

**Comment by eriknylund** [comment]
> > How come there is no option to receive to `Bech32m (Taproot)` address type when the wallet is encrypted? 🤔
> 
> Tested on Ubuntu 22.04. Confirming the bug for a just created wallet. Closing the wallet, and following re-opening it could be a temporarily workaround.

Thanks for testing @hebasto! I tried the File menu options `Close Wallet...` and `Close All Wallets...` and then tried re-opening it.  For me, the Taproot option is still unavailable. 

Another thing that strikes me as I reopen, shouldn't it be asking me for the password then? Right now I'm only asked to provide the password when I send a transaction. So it seems only part of the wallet is encrypted.

This led me to another test. If I start out with another new, unencrypted wallet and then Go to `Settings > Encrypt Wallet...` after encrypting this wallet, the Taproot receive option is available on **both** the old and new new encrypted wallet.

Even after closing and reopening wallets, all four receive types are present.

**Comment by stickies-v** [comment]
> For Apple M1 testers like me jumping straight at the binary, a section about how to configure for signet could be good.

The signet configuration is provided at the beginning of [Testing the GUI](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide#testing-the-gui) and this works when using the precompiled binaries too (I'm pointing to the .tar.gz binaries mostly for that reason), but I've added a link to your comment to help people that are not launching the GUI from cli. Thank you for providing the write-up with screenshots. (note: you might be interested in [#414 GUI](https://github.com/bitcoin-core/gui/pull/414) for ongoing discussion).

I've just created [#24706](https://github.com/bitcoin/bitcoin/issues/24706) as a feedback tracker for the testing guide, so please feel free to add any more thoughts there if you have them.

**Comment by eriknylund** [comment]
I'm running the IBD on mainnet as a part of my testing, and I've been switching back and forth between mainnet and signet to test the encrypted wallets and other transaction tests. Because of limited disk space on my M1 I'm on the default settings with a pruned node.

![image](https://user-images.githubusercontent.com/20860124/160593344-47a9c569-ef88-48e7-b3f4-7d46dd9831c1.png)
![image](https://user-images.githubusercontent.com/20860124/160593367-b51f0559-0d84-4acd-a038-db0a5beb6295.png)

Now all of a sudden my mainnet wallets are broken:

First I received this error message:
![image](https://user-images.githubusercontent.com/20860124/160592413-fed8d666-da31-4532-8ccc-660529b3797a.png)
Then it changed into:
![image](https://user-images.githubusercontent.com/20860124/160592444-c9063dae-62fe-4e9c-92d9-eb523bf46591.png)
I am able to create a completely new wallet and open that, but the old ones are no longer working. I have only one instance of Bitcoin Core running.

I restarted Bitcoin Core and now all wallets open again. So perhaps it wasn't to do with the signet/mainnet after all.

**Comment by laanwj** [comment]
> The testing guide is now available on https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide , @laanwj could you please add that link to OP?

Added, thanks!

**Comment by brunoerg** [comment]
Tested on MacBook Air (M1, 2020) - macOS Monterey - v12.0.1
I compiled it from source - v23.0rc2 

I ran the functional tests using `test_runner.py`, 4 tests failed (not related to this release but some tests fail here when running with `test_runner`), anyway, I executed that tests individually and got no failures. Also, unit tests ran succesfully.

I followed the [guide](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/23.0-Release-Candidate-Testing-Guide) to test the non-default ports and it worked successfully!

**Comment by hebasto** [comment]
> > How come there is no option to receive to `Bech32m (Taproot)` address type when the wallet is encrypted? thinking
> 
> Tested on Ubuntu 22.04. Confirming the bug for a just created wallet. Closing the wallet, and following re-opening it could be a temporarily workaround.

A fixed has been suggested in bitcoin/bitcoin#24711.

**Comment by fujicoin** [comment]
Environment: Ubuntu 20.04 Desktop on VMware WS 16
Binary: bitcoin-23.0rc2-x86_64-linux-gnu.tar.gz 15-Mar-2022 19:32 44188780
Problem: Does not start

```
$ ./bitcoin-qt -regtest &
./bitcoin-qt: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory
```

On Ubuntu 21.04 qt boots fine.
Is it a specification that does not support Ubuntu 20.04 or lower?

**Comment by hebasto** [comment]
@fujicoin 

```
$ sudo apt-get install libxcb-xinerama0
```
?

**Comment by fujicoin** [comment]
@hebasto
Wasn't all the required libraries built with static link in past versions?

**Comment by hebasto** [comment]
> @hebasto Wasn't all the required libraries built with static link in past versions?

This is a Qt 5.15 runtime dependency introduced in https://github.com/bitcoin/bitcoin/pull/23489.

See details:
- https://github.com/bitcoin/bitcoin/blob/v23.0rc2/contrib/devtools/symbol-check.py#L119
- https://doc.qt.io/qt-5/linux-requirements.html

**Comment by eriknylund** [comment]
My test feedback is available here https://gist.github.com/eriknylund/768787a123ed981d4bf824995bdda733 if you prefer I can submit the full feedback in this thread as well.

The error dialogs when opening a wallet resurfaced (see https://github.com/bitcoin/bitcoin/issues/24501#issuecomment-1081712948 above) and I'm a bit concerned about it and what it would mean for an unexperienced user. 

![image](https://user-images.githubusercontent.com/20860124/160990255-8fea3ef9-b876-4c32-8bec-8972827abe63.png)

Could you give me some insight on what this means and is it perhaps more likely to occur during the IBD? I guess most users will start off with a pruned node, with it being the default setting, and are more likely to run into this?

Please see the last section https://gist.github.com/eriknylund/768787a123ed981d4bf824995bdda733#ux-considerations for some ideas on UI/UX improvements.

**Comment by hebasto** [comment]
Fellow testers who is able/willing to test ARM binaries!

Please test #24115. On supported platforms the `Using the 'arm_shani(1way,2way)' SHA256 implementation` in the log is expected.

cc @stickies-v @prusnak

**Comment by eriknylund** [comment]
> Fellow testers who is able/willing to test ARM binaries!
> 
> Please test #24115. On supported platforms the `Using the 'arm_shani(1way,2way)' SHA256 implementation` is expected in the log.
> 
> cc @stickies-v @prusnak

Tested on:
    Apple M1 MacBook Pro (13-inch, M1, 2020)
    macOS Big Sur 11.6.4 (20G417)
    23.0rc2-arm64 binary

Does not match expected output in `debug.log`.
```
2022-04-01T07:25:10Z Using the 'standard' SHA256 implementation
```

**Comment by laanwj** [comment]
@eriknylund what does this give for output on your system:
```
sysctl -a | grep hw.optional.arm.FEAT_SHA256
```

**Comment by prusnak** [comment]
On my system:
```
❯ sysctl -a | grep hw.optional.arm.FEAT_SHA256
hw.optional.arm.FEAT_SHA256: 1
```

v23.0.0rc2 says:

```
2022-04-02T10:32:47Z Using the 'arm_shani(1way,2way)' SHA256 implementation
```

 v23.0.0rc3 says:

```
2022-04-02T10:34:30Z Using the 'arm_shani(1way,2way)' SHA256 implementation
```

**Comment by stickies-v** [comment]
Tested on:
Apple M1 Macbook Pro (14-inch, M1 Pro, 2021)


Matches expected output in debug.log:
```
2022-04-02T10:31:53Z Using the 'arm_shani(1way,2way)' SHA256 implementation
```

**Comment by prusnak** [comment]
Hm, maybe macOS 11.x reports `hw.optional.arm.FEAT_SHA256` inaccurately? Let's wait for what @eriknylund will report back.

**Comment by hebasto** [comment]
Fellow testers who run Bitcoin Core on macOS Monterey.

Please postpone the Monterey 12.3.1 update until 23.0rc4 to test whether #23134 has been really fixed.

**Comment by eriknylund** [comment]
> Hm, maybe macOS 11.x reports `hw.optional.arm.FEAT_SHA256` inaccurately?
> 
> Let's wait for what @eriknylund will report back about `sysctl` output.
> 
> Edit: Yes, that's it! See [dotnet/runtime#62832 (comment)](https://github.com/dotnet/runtime/issues/62832#issuecomment-994754094) - macOS 11.x does not report `hw.optional.arm.*` in `sysctl -a`.
> 
> I think we are fine. If the OS does not report the feature, we should not be using it; plus this is an opt-in optimization. Finally, most of people with M1 hardware will be running macOS 12.x anyway (because that's what being preinstalled since October 2021).

@prusnak unfortunately I won't reach this computer for some time but hopefully you found your answer already. I'll make sure to verify the above when I'm able to.

**Comment by laanwj** [comment]
> I think we are fine. If the OS does not report the feature, we should not be using it; 

Agree, this is the best kind of problem, it only marginally affects performance and will solve itself in time simply by updating the underlying OS. Nothing to do here.

**Comment by hebasto** [comment]
> Fellow testers who run Bitcoin Core on macOS Monterey.
> 
> Please postpone the Monterey 12.3.1 update until 23.0rc4 to test whether #23134 has been really fixed.

I've managed to sign v23.0rc3 (using [this](https://github.com/bitcoin/bitcoin/pull/24733/commits/7762c5683f91a066cf833a19e7c0153942395cb1) patch), and did apply the Monterey 12.3.1 update both on Intel based and Apple Silicon based systems. The previously installed Bitcoin Core v23.0rc3 has survived. #23134 is indeed fixed.

**Comment by dunxen** [comment]
Tested on:

iMac (Retina 5K, 27-inch, 2017)
macOS 12.3.1 (Didn’t see hebasto’s comment in time 😅)
Compiled from source at tag `v23.0rc3`

Findings: 

* Compilation successful
* Confirmed that creating an encrypted wallet in the GUI results in me not being able to select a bech32m address type (option is missing). I see this has been addressed in  #24711  which is merged and backported. I have tested that and it works as expected with the patch.
* Tested non-default ports and works as expected. After a while I was connected to an IPv4 peer with port 24355 on mainnet.
* CJDNS: Have been testing this long before #23077 was merged and it’s been working without issues ever since.

**Comment by hebasto** [comment]
Btw, users of localized GUI could test that no shortcut ambiguities have been introduced during translation.

**Comment by jsarenik** [comment]
Running latest Bitcoin from `23.x` branch + rebased [Yggdrasil patches](https://github.com/bitcoin/bitcoin/pull/23531) + [Alpine Linux locales fix](https://git.alpinelinux.org/aports/tree/community/bitcoin/use-c-locale.patch) at `ln.anyone.eu.org` ([btc-rpc-explorer](https://github.com/janoside/btc-rpc-explorer) (Bitcoin Explorer — BE) at [be.anyone.eu.org](https://be.anyone.eu.org/)). Works fine, no GUI and no recent Mac here (had a look at the testing guide), just Linux on old MacBookPro `x86_64`.

**Comment by Rspigler** [comment]
Compiled v23.0rc4 on Debian x86.  Ran all tests.  Was able to set up CJDNS, Tor and i2p connections.

**Comment by jonatack** [comment]
Ran the rc4 linux binary [bitcoin-23.0rc4-x86_64-linux-gnu.tar.gz](https://bitcoincore.org/bin/bitcoin-core-23.0/test.rc4/bitcoin-23.0rc4-x86_64-linux-gnu.tar.gz) on mainnet for an hour and some CLI/RPC commands. Ran the GUI at the same time on signet, checked various tabs and did various operations.

**Comment by hebasto** [comment]
Cross-posting a confirmed GUI bug on Windows: bitcoin-core/gui#582.

**Comment by prusnak** [comment]
> Please postpone the Monterey 12.3.1 update until 23.0rc4 to test whether #23134 has been really fixed.

Installed 23.0rc4 and updated macOS from 12.3 to 12.3.1 -> Bitcoin Core was not removed => https://github.com/bitcoin/bitcoin/issues/23134 is fixed

**Comment by stickies-v** [comment]
> Please postpone the Monterey 12.3.1 update until 23.0rc4 to test whether https://github.com/bitcoin/bitcoin/issues/23134 has been really fixed.

^ same here, 23.0rc4 kept working fine after updating from 12.3 to 12.3.1 (M1 Pro).

**Comment by landabaso** [comment]
> > I think we are fine. If the OS does not report the feature, we should not be using it;
> 
> Agree, this is the best kind of problem, it only marginally affects performance and will solve itself in time simply by updating the underlying OS. Nothing to do here.

I'm experiencing performance issues with v23 on macos, but I'm running it on an Intel macbook pro mid 2015 with Big Sur.
Mining is x10 slower with v23 than v22 (I need to mine on the regtest for integration testing purposes).
Can it be related to what you described?

I described the [issue on stack exchange](https://bitcoin.stackexchange.com/questions/113898/bitcoin-v23-is-10-times-slower-than-v22-in-macos-for-basic-regtest-tests).
