### ISSUE TITLE
Libbitcoinkernel Project Tracking

### ISSUE THREAD

**Issue by TheCharlatan** [bitcoin/bitcoin#27587]
#### Project Board: https://github.com/bitcoin/bitcoin/projects/18

This is the tracking issue for the `libbitcoinkernel` project. The original tracking issue is found in https://github.com/bitcoin/bitcoin/issues/24303. This issue contains much of the content written by Carl Dong in the original issue but is more regularly updated.

The libbitcoinkernel project is a new attempt at extracting our consensus engine. The kernel part of the name highlights one of the key functional differences from libbitcoinconsensus and in fact, most libraries: it is a stateful library that can spawn threads, do caching, do I/O, and many other things that one may not normally expect from a library.

This statefulness is necessary for libbitcoinkernel's decidedly incremental approach to extracting our consensus engine. This approach favors:

1. Reusing existing code
...which allows us to be continually integrated with Bitcoin Core and benefit from our extensive test suite
    
2. Incremental decoupling instead of building from scratch
 ...which allows us to avoid having to prematurely optimize for a "perfect" boundary or API (tends to be highly subjective, non-obvious, may lead to unproductive bike-shedding before we've even done anything meaningful)

The work of extracting our consensus engine into a library and making the API ergonomic is likely to be a multi-release project involving multiple contributors. The incremental approach takes this into account and respects the sheer size of work (both in writing code and getting it through review) that needs to be undertaken.

## PRs

Please see the project board: https://github.com/bitcoin/bitcoin/projects/18

## The Game Plan

* [ ] Stage 1
    * [x] Step 1
    * [ ] Step 2
    * [ ] Step 3
    * [ ] Step 4
    * [ ] Step 5
* [ ] Stage 2

##### a.k.a. What `.cpp` files do we need?

This `bitcoin-chainstate` executable uses our consensus engine and its build system code will reveal the minimal set of files we need to link in to use our consensus engine as-is. It is important to note that this list of files will serve as a guiding "North Star" for this first stage of the plan: as we decouple more and more modules of the codebase from our consensus engine, this list will grow shorter and shorter.

This list of files (the `_SOURCES` in `Automake` speak) then serves as the basis for a `libbitcoinkernel`, which `bitcoin-chainstate` will be linked against.

**Key Result:** Any further coupling of our consensus engine with non-consensus modules will result in linker errors, preventing this project from becoming a Sisyphean task of battling coupling regressions.
##### a.k.a. Prune the unnecessary `.cpp` files!

There are many modules that do not logically belong in `libbitcoinkernel` (e.g. `index/*.cpp`, `netaddress.cpp`), but are nevertheless necessary to be included in its `_SOURCES` for `bitcoin-chainstate` to link correctly. This is because Bitcoin Core's existing codebase is full of unnecessary dependencies/couplings that need to be untangled/decoupled/broken up.

The following list is likely incomplete but notes some of the to be pruned files:

  1. ~~`netaddress.cpp`~~
  2. ~~Parts of `timedata.cpp`~~
  3. ~~Parts of `init/common.cpp`~~
  4. `ArgsManager` (this one's a doozy)
  5. ~~`index/*.cpp`~~
  6. `shutdown.cpp`

**Developer Note:** We do not decouple the mempool _yet_ because most users of `libbitcoinkernel` may want to have an embedded mempool with Bitcoin Core's policies and we can decouple it later.

##### a.k.a. What `.h` files do we need?

Before this step, `bitcoin-chainstate` has been an internal executable managed by our build system with access to all files and headers. In this step, we add an external `bitcoin-chainstate` with a separate build system to reveal the minimal set of headers we need to ship in order to make the `libbitcoinkernel` library usable.

##### a.k.a. Prune the unnecessary `.h` files!

Similar to Step 2, there are lots of small decoupling of the header dependency tree here. A notable piece of this step is to remove `leveldb` includes from our headers to avoid needing to re-ship `leveldb` headers.

#### Step 5: Use the `libbitcoinkernel` library for internal compilation

Now that `libbitcoinkernel` contains some minimal set of source files, it should also be used as an internal library for `libbitcoin_node`. The desired library organization is shown in [doc/design/libraries.md](https://github.com/bitcoin/bitcoin/blob/master/doc/design/libraries.md).

### Stage 2: Polishing the API / Continual De-coupling

At this point, we have a usable `libbitcoinkernel` that is _somewhat_ minimally linked. However, it has a very idiosyncratic, Bitcoin Core-specific C++ interface. The goal of this stage is to incrementally make the `libbitcoinkernel` API more ergonomic for users outside of Bitcoin Core. Bindings to other languages (first C, then others) should be introduced. Note though, that there is a possible dichotomy here between optimizing the library interface for external users and for the internal interface within Bitcoin Core.

It is crucial that multiple contributors collaboratively lead this stage. Ideally, they would be able to work with users looking to integrate with `libbitcoinkernel` who can give an accurate account of the API ergonomics from the library user's point of view.

## Getting `libbitcoinkernel` Through Review

The following ground rules were proposed to make this process more streamlined for all parties involved and a few things this tracking issue can help with:

1. Any outstanding comments/reviews not pertinent to the main thrust of PRs should not delay/block the merging of the core functionality of PRs. Any leftover comments/reviews not tackled in the PR will be taken note of in the TODO section above and then either triaged in an issue or addressed in a separate PR.     
2. Whenever the PR reaches a stage where there are only leftover comments/reviews left, the author should make a comment saying so. This might make it easier for maintainers to determine roughly where the PR is at in its lifecycle.

## Action Items

1. If you have any questions, please post them below!
 2. If you plan on reviewing `libbitcoinkernel` or are a maintainer:       
       1. Please make sure you've read the "Getting `libbitcoinkernel` Through Review" section above.
       2. Please let me know if there's anything else I can do to help streamline the review process.
3. If you have any ideas for the future direction of "Stage 2: Polishing the API / Continual De-coupling", please leave a comment below, I'd love to talk!

## Project-wide TODOs

These are suggestions for further cleanup and improvements that came up during review:

* [ ]  Various followups for [[kernel 2c/n] Introduce `kernel::Context`, encapsulate global init/teardown #25065](https://github.com/bitcoin/bitcoin/pull/25065)
  
  * [ ]  Marco's post-merge review comments: [[kernel 2c/n] Introduce `kernel::Context`, encapsulate global init/teardown #25065 (review)](https://github.com/bitcoin/bitcoin/pull/25065#pullrequestreview-996614232)
  * [ ]  Cory's `kernel::Context` cleanup suggestions: [[kernel 2c/n] Introduce `kernel::Context`, encapsulate global init/teardown #25065 (comment)](https://github.com/bitcoin/bitcoin/pull/25065#discussion_r882182549)

* [ ]  Ryan's post-merge review comment: [[kernel 2e/n] miner: Make `mempool` optional, stop constructing temporary empty mempools #25223 (comment)](https://github.com/bitcoin/bitcoin/pull/25223#discussion_r898164322)

* [ ]  Various followups for [[kernel 3a/n] Decouple `CTxMemPool` from `ArgsManager` #25290](https://github.com/bitcoin/bitcoin/pull/25290)
  
  * [ ]  Perform gArgs checking in `ApplyArgsManOptions`: [[kernel 3a/n] Decouple `CTxMemPool` from `ArgsManager` #25290 (comment)](https://github.com/bitcoin/bitcoin/pull/25290#discussion_r907535652)
  * [ ]  Perform `CTxMemPool::Options` checking in `CTxMemPool` constructor: [[kernel 3a/n] Decouple `CTxMemPool` from `ArgsManager` #25290 (comment)](https://github.com/bitcoin/bitcoin/pull/25290#discussion_r900272797)
  * [ ]  Change `CalculateMemPoolAncestors` to take in `CTxMemPool::Limits` instead: [[kernel 3a/n] Decouple `CTxMemPool` from `ArgsManager` #25290 (comment)](https://github.com/bitcoin/bitcoin/pull/25290#discussion_r905260891)

* [ ]  Various followups for [[kernel 3b/n] Decouple `{Dump,Load}Mempool` from `ArgsManager` #25487](https://github.com/bitcoin/bitcoin/pull/25487)
  
  * [ ]  Improve `DumpMempool`'s mutex: [[kernel 3b/n] Decouple `{Dump,Load}Mempool` from `ArgsManager` #25487 (comment)](https://github.com/bitcoin/bitcoin/pull/25487#discussion_r916228022)
  * [ ]  Change `LoadMempool`'s semantics: [[kernel 3b/n] Decouple `{Dump,Load}Mempool` from `ArgsManager` #25487 (comment)](https://github.com/bitcoin/bitcoin/pull/25487#discussion_r916044902)
  * [ ]  Make LoadMempool less foot-gunny: [[kernel 3b/n] Decouple `{Dump,Load}Mempool` from `ArgsManager` #25487 (comment)](https://github.com/bitcoin/bitcoin/pull/25487#discussion_r921234107), [c4249c1](https://github.com/bitcoin/bitcoin/commit/c4249c1243981f42091950d1295c2be6bd4bf118)

* [ ] Various followups for [refactor, kernel: Decouple ArgsManager from blockstorage #27125](https://github.com/bitcoin/bitcoin/pull/27125)
  * [ ] Marco's request for a minimal iwyu memory include false positive example: https://github.com/bitcoin/bitcoin/pull/27125#discussion_r1184832621

**Comment by willcl-ark** [comment]
Would it make sense to update the project page to https://github.com/orgs/bitcoin/projects/3/views/1 (which if I'm not mistaken seems to be the current one)?

Could keep a link to the old project https://github.com/bitcoin/bitcoin/projects/18 for reference?

**Comment by TheCharlatan** [comment]
Re https://github.com/bitcoin/bitcoin/issues/27587#issuecomment-1568419077
 
 > Would it make sense to update the project page to https://github.com/orgs/bitcoin/projects/3/views/1 (which if I'm not mistaken seems to be the current one)?
 
 Thanks for the notice, updated to the new one.
 
 > Could keep a link to the old project https://github.com/bitcoin/bitcoin/projects/18 for reference?
 
 There is no useful extra information on the old board that is not in the new one, so I don't think this is necessary.

**Comment by darosior** [comment]
@TheCharlatan sometimes mentions [sourcetrail](https://github.com/CoatiSoftware/Sourcetrail) as a tool to visually inspect the currently required kernel headers. I've set it up and figured it could be worth sharing with anyone who's interested in having a quick look to the trail of headers without having to set up the tool themselves.

The list of headers included in libbitcoinkernel as of current master d2ccca253f4294b8f480e1d192913f4985a1af08:
![bitcoin-chainstate_sourcetrail](https://github.com/bitcoin/bitcoin/assets/22457751/5dd5c049-35df-4e74-a52f-7453efa5f0e3)

**Comment by fanquake** [comment]
Nice. Played around with this. If you merge a couple things, and turn on c++20, so we can use `<bit>` (see corys branch), `bitcoin-config.h` disappears:

![less_headers](https://github.com/bitcoin/bitcoin/assets/863730/67408e5c-39f5-4a76-98a3-63ae340afdbb)

**Comment by Sapibeltv** [comment]
We are sapibel families and Seexy Nadege Entertainment 2vtv and SAPIBELTVradio is the most important tools to use the internet marketing industry provider https://github.com/bitcoin/bitcoin/assets/107956561/38841f2f-3194-4f66-aa76-9eeb96988216

**Comment by medobrens83** [comment]
👍👍🏻💯

**Comment by sedited** [comment]
I re-wrote the tracking issue. It now better reflects all the different areas being worked on and also surfaces a lot of the work I have not opened a pull request for.

**Comment by moonfury-ops** [comment]
Hello @TheCharlatan 

I’m particularly interested in the following areas:

API design and language bindings — I’d be happy to contribute or test bindings for additional environments such as JavaScript, Kotlin, or Dart.
Read-only clients and context-minimal validation — These directions align well with lightweight and alternative Bitcoin client use cases. Abstracting data storage and validation dependencies is a meaningful step toward broader adoption.
Standalone repository plans — The goal of making the kernel independently usable and testable is compelling. 
I’d be interested in contributing to the CI setup or test framework design if needed.

**Comment by yuvicc** [comment]
> I’d be happy to contribute or test bindings for additional environments such as JavaScript, Kotlin, or Dart.

I think you can start off with javascript language bindings. See the C API header PR -> https://github.com/bitcoin/bitcoin/pull/30595

**Comment by Sjors** [comment]
I vibe coded a proof-of-concept iOs / macOS kernel based "node" that syncs blocks from mempool.space: https://github.com/Sjors/kernel-i-node

It's gotten a _lot_ easier than when I tried this for #11720 almost a decade ago.

**Comment by musaHaruna** [comment]
Hi @sedited , I have been reviewing Kernel project issues and several pull requests to better understand the project so I can contribute meaningfully. Recently, I have been studying this outstanding [TODO](https://github.com/bitcoin/bitcoin/pull/27636#discussion_r1202937682), and although I have thought about it, I am still struggling to fully reason about it. Below is my understanding and a naive approach I considered for implementing the TODO, which I suspect has some limitations.

### My understanding of the issue
Currently, the validation layer sends block-tip notifications using `const CBlockIndex&`. This is an internal Bitcoin Core structure that contains a large amount of chain state and metadata.

However, many consumers of this notification do not actually require the full `CBlockIndex`. For example, the UI layer ultimately converts it into a much smaller abstraction `BlockTip`.

The long-term concern is architectural as stated [here](https://github.com/bitcoin/bitcoin/pull/27636#discussion_r1204902245https://github.com/bitcoin/bitcoin/pull/27636#discussion_r1204902245) we should avoid exposing internal Core structures across subsystem boundaries, especially in preparation for a future public kernel API. If `CBlockIndex` were exposed externally, then any internal changes to it could introduce API or ABI breakage for external users. This would tightly couple external code to Bitcoin Core internals.

To prevent this, a lightweight wrapper such as `BlockTip` would preferred, since it exposes only stable, minimal information.

### Current data flow
From what I understand, the flow currently works like this:

1. In `validation.cpp`, inside `Chainstate::ActivateBestChain()`, when a new best tip is connected, the code calls `m_chainman.GetNotifications().blockTip(..., *pindexNewTip, ...)`
2. This sends a `CBlockIndex` through the kernel notification layer.
3. In `KernelNotifications::blockTip()`, the node layer receives the `CBlockIndex` and forwards it to the UI system `uiInterface.NotifyBlockTip(state, index, verification_progress);`
4. Finally, the UI layer converts the internal `CBlockIndex` into a lightweight `interfaces::BlockTip` (`BlockTip{block.nHeight, block.GetBlockTime(), block.GetBlockHash()}`)
 

### My proposed change
My approach is to refactor the block-tip notification path so that `CBlockIndex` is no longer passed outside the validation layer.
Instead, when a block-tip notification is generated, the code immediately converts `CBlockIndex` into a lightweight `BlockTip` structure containing only: block height, block time, block hash. This simplified object is then passed through the rest of the system.

The complete code change can be found on my branch [here](https://github.com/bitcoin/bitcoin/compare/master...musaHaruna:bitcoin:refactor/remove-cblockindex-from-notifications)

### What I changed

- At the kernel boundary, I modified `kernel::Notifications::blockTip(...)` to use the `BlockTip` wrapper instead of `CBlockIndex`.
- In `validation.cpp`, I perform the conversion from `CBlockIndex`to `BlockTip` at the point where the notification is created.
- On the node and UI side, I reused `interfaces::BlockTip` and moved it to `src/interfaces/types.h`.
- I updated `uiInterface.NotifyBlockTip` so it now receives the simplified `BlockTip` directly instead of reconstructing it later.
- As a result, `handleNotifyBlockTip(...)` no longer needs to rebuild the tip data and can forward it directly.
- For `libbitcoinkernel`, I introduced a simple `btck_BlockTip` struct in `src/kernel/bitcoinkernel.h`, and updated the wrapper and example code accordingly.

### Core idea behind the change
The main idea is to convert `CBlockIndex` into a minimal representation once at the point of notification creation, and pass only the lightweight structure downstream.

This reduces coupling and prevents internal data structures from leaking across subsystem boundaries.

### Additional note
Regarding RPC impact: I am not fully certain how the change is expected to propagate there. In my branch, it did not require modifications in `src/rpc/*`. The only additional place I had to update outside the kernel and node notification flow was the `-blocknotify` hook in `src/init.cpp`, since it also listens to block-tip events.

Finally, I should mention that in my branch I did not strictly follow the conventional handle/view pattern, as I was mainly experimenting to understand the flow.

**Comment by sedited** [comment]
> I have been reviewing Kernel project issues and several pull requests to better understand the project so I can contribute meaningfully. Recently, I have been studying this outstanding https://github.com/bitcoin/bitcoin/pull/27636#discussion_r1202937682, and although I have thought about it, I am still struggling to fully reason about it. Below is my understanding and a naive approach I considered for implementing the TODO, which I suspect has some limitations.

@musaHaruna Thank you for taking the time to go through this exercise, this is how I would have solved it too. I was never sure about authoring this change myself, because the same types are still being passed through the validation interface too. Removing them there seems a bit more involved, so I wasn't convinced that this would provide enough utility by itself to warrant the change. Your change is quite self-contained, and it would be nice to have at least one interface not push out internal types, but I'm not sure if it is worth it at this point in time.

**Comment by janb84** [comment]
We discussed that there should be a list of missing kernel functions, see this as a starter for discussions.

**Transaction acceptance checking** (broadly useful): 
mempool acceptance (`btck_chainstate_manager_process_transaction`), (wraps `ChainstateManager::ProcessTransaction`, i.e. mempool acceptance / policy validation), with a `btck_TxValidationState*` out-param like `btck_transaction_check`
package acceptance (`btck_chainstate_manager_process_package`) package/CPFP validation

**UTXO point lookup** (broadly useful): 
coin lookup by outpoint (`btck_chainstate_manager_get_coin`) returns `btck_Coin*` 

**Operational basics** (broadly useful): 
explicit flush (`btck_chainstate_manager_flush`), 
IBD predicate (`btck_chainstate_manager_is_initial_block_download`), 
verification progress (`btck_chainstate_manager_guess_verification_progress`), 
cache sizes (`btck_chainstate_manager_options_set_total_cache_size`), 
pruning (`btck_chainstate_manager_options_set_prune_target_bytes`, `btck_chainstate_manager_prune_up_to_height`)

**Chain surgery and recovery** (Possible interesting ? ): 
invalidate/reconsider block (`btck_chainstate_manager_invalidate_block`, `btck_chainstate_manager_reconsider_block`), 
integrity check (`btck_chainstate_manager_verify_db`)

**Chain event callbacks** (broadly useful): 
`btck_ValidationInterfaceUpdatedBlockTip`, `btck_ValidationInterfaceActiveTipChange`, `btck_ValidationInterfaceChainStateFlushed`

**Transaction-level accessors** (broadly useful): 
version/wtxid/weight/sizes (`btck_transaction_get_version`, `btck_transaction_get_wtxid`, `btck_transaction_get_weight`, `btck_transaction_get_virtual_size`, `btck_transaction_get_total_size`), 
scriptSig + witness (`btck_transaction_input_get_script_sig`, `btck_transaction_input_get_witness`), 
txid from bytes (`btck_txid_create`), 
merkle root (`btck_block_header_get_merkle_root`) needed for SPV-style merkle proof checking

**Chain metadata and parameters** (low prio): 
chain work (`btck_block_tree_entry_get_chain_work`), 
transaction count (`btck_block_tree_entry_count_transactions`), 
median-time-past (`btck_block_tree_entry_get_median_time_past`), 
consensus params (`btck_consensus_params_get_*`), genesis (`btck_chain_get_genesis`)

Below the fold stuff (low prio, if et al, see comment [below](https://github.com/bitcoin/bitcoin/issues/27587#issuecomment-4927858674))

**Mempool event callbacks** (Possible interesting ? ): 
`btck_ValidationInterfaceTransactionAddedToMempool`, `btck_ValidationInterfaceTransactionRemovedFromMempool`, `btck_ValidationInterfaceMempoolTransactionsRemovedForBlock`; 

AssumeUTXO (`btck_chainstate_manager_activate_snapshot`), 

**Hosted mempool** (Possible interesting ?): 
options (`btck_mempool_options_create` + setters), 
query surface (`btck_chainstate_manager_get_mempool`, `btck_mempool_count`, `btck_mempool_contains`, `btck_mempool_get_entry_by_txid`, `btck_mempool_entry_get_*`)

**Comment by sedited** [comment]
Thanks for collecting those @janb84. I think we shouldn't be adding mempool and assumeutxo utilities any time soon. In my opinion clients should rather be thinking about how they can implement these features themselves and request the necessary functions and callback hooks from us. I am now linking to this list in the tracking issue.

**Comment by starius** [comment]
I want to comment on "Compile targets for embedded, web assembly, and proof systems" section of the issue and propose some changes.

I'm trying to implement a RISC-V zkVM guest running a confidential version of proof-of-funds BIP-322 scheme.

The guest needs roughly this function:

```c
verify_script(tx_bytes, prevouts, input_index, flags) -> result_code
```

The function can't call OS, in particular it can't do IO and can't work with OS threads.

I propose these changes in the kernel library to enable this:

- a build mode that does not link pthreads or require OS thread support (a build option like `BITCOIN_SINGLE_THREADED`)
- a Script-verification-only kernel build target, so the resulting binary does not include chainstate, LevelDB, block storage, filesystem-dependent code, or unrelated kernel objects (`BITCOIN_KERNEL_SCRIPT_ONLY`)
- a way to build this target for constrained cross-compilation environments, such as RISC-V bare metal / zkVM targets (a set of CMake options)
  - For some targets this may also need caller-controlled allocation or a custom allocator hook.

The existing C header `bitcoinkernel.h` already exposes Script-related types and functions (e.g. `btck_script_pubkey_verify`). I propose to provide them as an small isolated sans-IO target.

I'm looking for feedback. I would like to implement this step-by-step, starting with `BITCOIN_SINGLE_THREADED` if that makes sense.

**Comment by fanquake** [comment]
@starius If you haven't seen it yet, you might be interested in taking a look at this recently merged PR: #31425. You can now use `-DCMAKE_SYSTEM_NAME=Generic`, which allows you to bypass needing pthreads, atomics, boost headers etc.

**Comment by starius** [comment]
@fanquake Thank you very much! This helped a lot!

What I need is `btck_script_pubkey_verify` function. Unfortunately I can't use the one provided by `src/kernel/bitcoinkernel.cpp` directly, because it is a part of `bitcoinkernel` library which is too large for my use case. It is too large for the guest path: chainstate, LevelDB, filesystem pieces, etc.

That is why I [copy-pasted](https://gist.github.com/starius/16f152b8fd639fb609508ccec4b0e2d0) `btck_script_pubkey_verify` and adapted it for my use case. The only dependencies from Bitcoin Core are now `bitcoin_consensus`, `bitcoin_crypto`, and `secp256k1`.

This works and works great, but I think we can refactor it so stock `btck_script_pubkey_verify` can be used from RISC0 directly:
 - expose a script-only embeddable target containing the official `btck_script_pubkey_verify` without pulling the full kernel source graph
 - make the function **allocation-free** to avoid overrides of `malloc` and friends (see my snippet above)

Inspired by [hyperscan API](https://intel.github.io/hyperscan/dev-reference/api_files.html), I propose the following API:
```c
int btck_script_verify_workspace_size(params..., size_t* out_size);

int btck_script_verify_with_workspace(
      params...,
      char* workspace_ptr,
      size_t workspace_len,
      btck_ScriptVerifyStatus* status
)

// Usage:

size_t workspace_len;
if (!btck_script_verify_workspace_size(..., &workspace_len)) {
  return error;
}

char* workspace_ptr = malloc(workspace_len);
if (workspace_ptr == NULL) {
  return error;
}

btck_ScriptVerifyStatus status;
if (!btck_script_verify_with_workspace(..., workspace_ptr, workspace_len, &status)) {
  return error;
}

// Handle status.
```
