### ISSUE TITLE
BIP352 tracking issue

### ISSUE THREAD

**Issue by josibake** [bitcoin/bitcoin#28536]
This issue will be updated to reflect the current state of [BIP352](https://github.com/bitcoin/bips/pull/1458) integration.

Testing:
* For a wallet with send and receive support, compile https://github.com/bitcoin/bitcoin/pull/28453
* Post your signet / testnet silent payment address in the comments!

PRs ready for review:

* https://github.com/bitcoin/bips/pull/1458
* https://github.com/bitcoin/bitcoin/pull/28122

Overall plan:

* Send and receive support in the Bitcoin Core wallet:
  - [x] Code cleanup / refactor: https://github.com/bitcoin/bitcoin/pull/28244
  - [x] Dependency: https://github.com/bitcoin/bitcoin/pull/28246
  - [ ] Base protocol: https://github.com/bitcoin/bitcoin/pull/28122
  - [ ] Sending (depends on 28122): https://github.com/bitcoin/bitcoin/pull/28201
  - [ ] Receiving (depends on 28122, 28201): https://github.com/bitcoin/bitcoin/pull/28453
  - [ ] Send and receive functional tests (depends on 28453) (not started)

* Light client support:
  - [ ] Index for silent payment tweaks (depends on 28122): https://github.com/bitcoin/bitcoin/pull/28241
  - [ ] New BIP157 filter type for tweak data (not started)
  - [ ] Serve new filter type (not started)

* Long-term
  - [ ] Move base protocol to `libsecp` as a module (not started)
  - [ ] Refactor Core to use silent payments `libsecp` module directly (not started)

<details>
  <summary>Older stuff</summary>

  <ul>
  <li>Closed / Superseded:
     <ul>
     <li>Tracking PR (superseded by this issue): #27827</li>
     <li>Receiving (superseded by 28453): #28202</li>
      <li>Original draft implementation: #24897</li>
      </ul>
  </li>
  </ul>
</details>

**Comment by josibake** [comment]
Review comments from #28246 that can be done as follow-ups:

- [ ] https://github.com/bitcoin/bitcoin/pull/28246#discussion_r1331393662
- [ ] https://github.com/bitcoin/bitcoin/pull/28246#discussion_r1331396058
- [ ] https://github.com/bitcoin/bitcoin/pull/28246#discussion_r1331396740

**Comment by josibake** [comment]
Signet address: `tsp1qqwzyz4wvrxnpauh9wj5x0lycvhhf0ff6gv0v0cyc6fcss7knlw3vzquefh7c4j7et3u0f059zw8zzyd97e6j4h4ldfs06t6pen9904w4fvpdukyc`

**Comment by setavenger** [comment]
@josibake Sent you some, using a light client so I hope this worked.

---
Signet:
`tsp1qqfnlnlnwwrcn7x09u0p0fm6l3698pw9s6mzlg6wv99dempzxmz53sqklscmpcwzkcmuvr4s503w220qgslyhfyxln3tqevfllmu6epvrlu5z457e`

**Comment by josibake** [comment]
@setavenger received, `0.00021000`! I tried sending it back but it appears your address is invalid. I'd like to keep this issue focused on the integration for Bitcoin Core, but feel free to join the silent payments IRC channel (`#silentpayments`) or reach out on twitter (`@josibake`) so we can keep testing!

**Comment by theStack** [comment]
>   * [ ]  Move base protocol to `libsecp` as a module (not started)

FWIW, I've started digging a bit deeper into that and started a corresponding discussion in the libsecp256k1 repo: https://github.com/bitcoin-core/secp256k1/issues/1427 (still trying to figure out a sane interface...)

**Comment by Sjors** [comment]
You can point to the actual BIP now in the description 🎉

**Comment by Turtlecute33** [comment]
<details>
<summary> Edit: I realized this isn't the right place to discuss this, hiding 
</summary>
I genuinely think silent payments are a good idea and plan on using them myself once they're production ready. However, I wonder if including silent payment support in Bitcoin Core is a good idea, or if instead it would be better to have a separate software on top of Bitcoin Core where the Silent Payments logic is handled - similar to how lightning network nodes or electrum servers are implemented.

From what I can see it will be possible to enable/disable Silent Payments support using the compilation flag, but most users don't compile Bitcoin Core, they download it from the official website, and if the official release binary will have Silent Payments activated, this means that a lot of users will have code they don't need in their nodes.
From my point of view, Bitcoin Core should remain as minimal as possible, to decrease the surface of possible attacks, and to make it easier to update and maintain.

I'm interested in exploring the reasons behind this choice. Sorry if this might not be the best place for discussion, in case, let me know where I can ask!
</details>

**Comment by josibake** [comment]
Hey @Turtlecute33 , this issue is meant to track the status of the PRs and keep track of any follow-ups that might arise. I don't think it's a good place for a general discussion on what should or shouldn't be in Bitcoin Core. I'm not sure of a good place for meta discussions about the project but I'm happy to continue this conversation in the #silentpayments IRC channel

**Comment by Eunovo** [comment]
> PRs ready for review:
> 
> * [Add BIP352 module (take 3) bitcoin-core/secp256k1#1698](https://github.com/bitcoin-core/secp256k1/pull/1698)

[Add BIP352 module (take 3) bitcoin-core/secp256k1#1698](https://github.com/bitcoin-core/secp256k1/pull/1698) has been replaced with  [Add "silentpayments" module implementing BIP352 (take 4, limited to full-node scanning)](https://github.com/bitcoin-core/secp256k1/pull/1765)

Anyone looking to try out silentpayments on bitcoin-core can use https://github.com/bitcoin/bitcoin/pull/32966, which has sending and receiving support and works on the bitcoin-core gui.

**Comment by PedroRosalba** [comment]
hey guys what is the status of this? If there are blockers can someone describe them?

**Comment by furszy** [comment]
> hey guys what is the status of this? If there are blockers can someone describe them?

Please read the message that is just above yours.

**Comment by multicryptobank** [comment]
We started trying out/testing silent payments on Bitcoin Core last year.

<img width="939" height="452" alt="Image" src="https://github.com/user-attachments/assets/29353977-570d-41eb-8706-9209f0ae3305" />

<img width="939" height="421" alt="Image" src="https://github.com/user-attachments/assets/695fc161-d8fa-428c-91e9-c6a9b73c6926" />

<img width="940" height="119" alt="Image" src="https://github.com/user-attachments/assets/03d53405-fcf8-4cff-bbc9-f00b954ab714" />

Any assistance, please reach out to us.

Cheers.
