### ISSUE TITLE
Embedded ASMap data Tracking Issue

### ISSUE THREAD

**Issue by fjahr** [bitcoin/bitcoin#28794]
This issue will be updated continuously to reflect the process of embedding ASMap data in Bitcoin Core, so asmap can be used without procuring an asmap file first. Having the asmap data available embedded is a requirement for potentially using it by default in the future. 

**PRs Ready for review:**
- https://github.com/bitcoin/bitcoin/pull/28793

**Looking for conceptual review:**
- https://github.com/bitcoin/bitcoin/pull/28792

**TODOs**

Implement means of embedding an ASMap file within a bitcoin core releases
- [ ] https://github.com/bitcoin/bitcoin/pull/28792
OR
- [ ] [WIP] Embedding asmap file during release build phase

Encoding tools available within Bitcoin Core
- [x] (optional) https://github.com/bitcoin/bitcoin/pull/28793

Analysis/logging of file performance
- [x] (optional) https://github.com/bitcoin/bitcoin/pull/27581

**Misc related topics**

Related topics like sourcing of input data, communication etc. that are outside of the scope of this repo will go here soon

**Comment by fjahr** [comment]
This issue hasn't seen much love but that's because there isn't much else to do by now in my mind, aside from #28792 and also most of the interesting action on ASMapt takes place outside of this repo, like in https://github.com/fjahr/asmap-data/ and https://github.com/fjahr/kartograf. So I am going to close this for now, the focus is on #28792 which should hopefully let us take the next step in adoption of this feature.

If we end up needing to put more work into ASMap than expected, I am happy to reopen this.

**Comment by average-gary** [comment]
Is there no way to query AS Maps directly from the BGP tables?

**Comment by fjahr** [comment]
> Is there no way to query AS Maps directly from the BGP tables?

Who's BGP table? Can you be a bit more specific what you are thinking of in terms of architecture and trust assumptions?

**Comment by joe-bp** [comment]
> > Is there no way to query AS Maps directly from the BGP tables?
> 
> Who's BGP table? Can you be a bit more specific what you are thinking of in terms of architecture and trust assumptions?

Hi Fabian, I've been talking to Gary about this a bit.  I submitted an issue here: https://github.com/asmap/asmap-data/issues/17

I'd like to propose a way to pull in the actual real-time BGP routing table and use that data for asmap.  Multiple people/orgs can do this independently and get the data from multiple networks.
