### ISSUE TITLE
AssumeUTXO Mainnet Readiness Tracking

### ISSUE THREAD

**Issue by fjahr** [bitcoin/bitcoin#29616]
## Goals of this issue

- Track all ongoing work on assumeutxo until mainnet params are included in a release
- Categorize the work into critical/optional for mainnet readiness
- Conceptual discussion on assumeutxo topics that may or may not be critical for mainnet readiness

The initial categorizations here are suggestions and changes should be discussed here in the issue. Obviously let me know if I missed anything.

## Critical Issues/PRs

- [x] #28553 - The mainnet params themselves
- [x] #29519 - Stop syncing non-snapshot chain from peers that are already connected
- [x] #30598 - Resolving #30514
- [x] #30320 - Deny loading if snapshot is not in best header chain
- [x] #29996 - Bugfix and additional test coverage
- [x] #29720 - RPC fixes for missing values, addressing #29328
- [x] #29612 (which fixes #25675) - Improves size of dump, critical because it is not backwards compatible
- [x] #29726 - Fix -reindex behavior
- [x] #29370 - Get rid of faked nTx and nChainTx values (closing issues discussed in #29261)
- [x] #30267 - Prevent issues from loading dump for invalid block

## Optional Issues/PRs

(Attempted a rough ordering by importance)

- [ ] #28616 (which fixes #28598) - Show background chain funds as not fully confirmed in GUI
- [ ] #30455 - Additional wallet tests
- [ ] #29553 - `dumptxoutset` with height param
- [ ] #30214 - First part of #28608
- [ ] #29993 - Improve usability
- [ ] #28608 (draft) - State and locking cleanup
- [x] #30636
- [x] #30497
- [x] #30403 - Additional test coverage and cleanup
- [x] #30388 - Optimization for testing performance
- [x] (obsolete) #28670 - Improved error handling for `loadtxoutset`
- [x] #29478 - Additional test coverage for `loadtxoutset`
- [x] #29617 - Additional test coverage
- [x] #29973 - Additional test coverage
- [x] #29428 - Additional test coverage

## Critical conceptual discussion

- [x] #30288
- [x] Agreement on a rule of thumb which height we choose once there is consensus for mainnet readiness, i.e. how to choose the height for #28553 once we are close to an upcoming release. I think the earlier we discuss this the better, so that this doesn't get in the way later.

## Optional conceptual discussion

These were taken from #28553 and [the original assumeutxo PR](https://github.com/bitcoin/bitcoin/pull/27596#issuecomment-1727936044).

- [ ] Distribution of snapshots - This recently came up [here](https://github.com/bitcoin/bitcoin/pull/29551#pullrequestreview-1917416713) and [here](https://bitcoin-irc.chaincode.com/bitcoin-core-dev/2024-03-07#1012635;). There are multiple levels to this topic but I believe that this is not critical either way. If it were critical then, at the most basic level, we would probably provide an "official" torrent/download link for the dump with the release. It would be great if one or more contributors could do that (@Sjors did this in #28516 for example) and are willing to maintain this for a reasonable amount of time but it is not critical IMO because anyone can use `dumptxoutset` to recreate the dump and then share it any way they like. So there is no need to provide this service from within the project. I think anyone who plans to distribute the dump to other users (think of downstream projects like BTCPayServer, Raspiblitz, Umbrel, Greenlight etc.) should validate the dump like this at least once anyway. And there may even be options for distribution possible for downstream projects that we can not even think of right now but if we don't make the feature available they can also not be explored.
- [ ] Usage of MuHash #27669 - While it would be nice to have this I don't think it is blocking because this can still be introduced later without invalidating existing dumps.
- [ ] Make params configurable/not hardcoded params - I think it would be good to stay on the safe side for now and make the feature available to the public as originally planned. If the feature sees wide adoption and requests for more flexibility come in that would be the right point to explore this further.
- [ ] Should old hashes be removed from source code at some point? - Obviously not relevant for the first mainnet params
- [ ] How frequently should we update testnet/signet params and is there any way to deal with the possibility that these chains [may get nuked at some point](https://x.com/kallewoof/status/1763222648367308958)?

**Comment by Sjors** [comment]
I think "Make params configurable/not hardcoded params" should be under "critical conceptual discussion". Not the part about flexibility, which I agree is low priority.

What's more fundamental is the question of whether these parameters should be "blessed" by the Bitcoin Core project.

One could argue that there is no "blessing", because these snapshots can be objectively assessed. A snapshot hash is valid if and only if background validation yields the same result. Any other snapshot, if it somehow makes into the code, is either a bug or an exploit.

This makes this feature different from checkpoints in a fundamental way. A checkpoint can be abused to override the most-work valid chain. Once enough people honor it, it becomes a fait accompli because miners are incentivised to work on it - eventually making it the most-work chain.

The same can't be achieved with an invalid snapshot. Such forgery can always be demonstrated as long as a single person has an archive of the blockchain all the way back to genesis.

Still, in a far future where perhaps few _users_ actually perform the background validation, a technically sound argument may not matter in the political reality.

A thought experiment to clarify this. The US Treasury finally issues their one trillion dollar coin. They do so by creating their own UTXO snapshot and forcing maintainers to include it. To avoid a chain split existing nodes on the network, they don't actually move the coin, but borrow against it. A few generations go by, more and more nodes will have be reinstalled and synced based on this new snapshot.

In this particular scenario I don't think it matters at all if the hash is part of chainparams or if it's flexible. But there may be a less extreme scenario's where it does. Which is why I think some discussion is warranted.

Meanwhile there is a major downside to not hardcoding the parameters, in that it makes the feature much harder to use. A user would have to find some place to download it, verify a hash and a PGP signature. It's less obvious how we could add p2p snapshot functionality later, because we have no hash to ask for and check against.

So on balance, because of the difference with checkpoints I explained above, my current thinking is that it's alright to include these params.

> How frequently should we update testnet/signet params

Imo those params are only there to test the functionality. They don't need to be fresh. If the are nuked, we can add new params a year after the new genesis block (it's hard to test this feature if the snapshot is too close to the start of the chain).

**Comment by Sjors** [comment]
That PR also gives us clean way to drop the `BLOCK_ASSUMED_VALID` flag, because it was never used on a mainnet node.

**Comment by fjahr** [comment]
Moved #29370 to the critical category

**Comment by luke-jr** [comment]
https://github.com/bitcoin/bitcoin/issues/28598 should be in critical

**Comment by Sjors** [comment]
> Can you say what you mean with "the part about flexibility" that is different from configurable params? I am not sure we are thinking of the same thing there.

Flexibility of which assumed valid block to load seems like a nice-to-have feature. I don't consider that important to discuss before merging mainnet.

> I am happy to have such discussion now but I don't think we need a resolution before anyone can use au on mainnet. If there is consensus for moving away from hardcoded params before we are done with the "critical" section here, then there will be PR that is added to the critical list that implements that functionality and the mainnet params PR will be removed from the list. If we merge the params first and then agree on not hardcoding them anymore, the params will simply be removed with that PR later.

It boils down to the age old wisdom that there's no such thing a temporary feature.

> For the alternative, configurable params, I am not so sure that it doesn't introduce new attack vectors and I think this hasn't been thought through enough because there was consensus to add the code with chainparams.

I don't think there was much discussion on the trade-offs between these two approaches.

I'm still inclined to think that including them is fine. As are you. But it seems "critical" that more people think this through. If nobody else chimes in with counter arguments for the v28 branch-off then I think we should just merge the mainnet params.

**Comment by Sjors** [comment]
@luke-jr I think it can wait until there's an easy GUI way to load a snapshot.

**Comment by Sjors** [comment]
> Ok, so the critical part would be to get this in front of some more people but if they just shrug it's also fine.

Exactly.

**Comment by fjahr** [comment]
> Why is #29720 / #29328 not mentioned here?

Because nobody else mentioned them here so far, tagged this issue in either or notified me about them.

**Comment by Sjors** [comment]
Definitely not a blocker: #29993

**Comment by fjahr** [comment]
> 29996 doesn't seem optional, but possibly a blocker, see [#29996 (comment)](https://github.com/bitcoin/bitcoin/pull/29996#discussion_r1632216319)

Thanks for notifying about the conversation there. So far it's still only a test PR and not a fix but if that changes I will move it. I think the actual issue discovered there is fixed in https://github.com/bitcoin/bitcoin/pull/30267 and I will put that in blockers for now.

**Comment by fjahr** [comment]
Moved up #29996 and added #30320 and #30288

**Comment by fjahr** [comment]
While there are still a few nice improvements to review and merge, this issue has achieved its main purpose and can be closed with the merge of #28553. If someone wants to open a follow-up issue that's great but I think as things stand now the existing open PRs are easy enough to keep track of.

It's also possible that we will see more new feedback come in when the feature starts to get adoption after the release of v28 but we can still open a follow-up issue that matches whatever structure we may need when the time comes.
