### ISSUE TITLE
Wallet fuzzing tracking issue

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#29901]
The wallet has poor fuzz coverage. Hopefully, some work is being done to improve it. The goal of this issue is to actively track current work and work that needs to be done to improve fuzz coverage for the wallet.

## Open PRs / Ready to review

- [ ] https://github.com/bitcoin/bitcoin/pull/29694
- [ ] https://github.com/bitcoin/bitcoin/pull/28236
- [ ] https://github.com/bitcoin/bitcoin/pull/28074

## Current wallet targets

We currently have 6 specific targets for wallet, which cover:

- Fees (`wallet/fees.cpp`)
- Coin selection
- ScriptPubKeyManager (descriptor)
- Coin control (`CCoinControl`)
- Notifications
- ISO8601 parser

## Nice to have

- [ ] Feebumper target
- [ ] More coverage for `CWallet` stuff
- [ ] Wallet transaction target
- [ ] Wallet receive target

### Legacy wallet removal

The goal is to remove legacy wallets and migrate them to descriptor ones. There is an open issue with a proposed timeline for Legacy Wallet and BDB removal (https://github.com/bitcoin/bitcoin/issues/20160). For this reason, we do not aim to increase fuzz coverage for legacy stuff. See that the `scriptpubkeyman` target only uses descriptor ones.

### External signer

I do believe we can't have fuzz coverage for external signer code.

## Performance and determinism

Unfortunately, some aspects of the wallet may affect the fuzzing performance.  E.g.:

- `SetupDescriptorScriptPubKeyMans` (it might also be non-deterministic due to key generation)
- Wallet encryption
- Wallet migration (there is a PR improving it - https://github.com/bitcoin/bitcoin/pull/28574)

----------------------

Any ideas about it or PRs to add let me know.

**Comment by brunoerg** [comment]
> Coverage is nice, but if the fuzz test never finds any real user-facing issues, it will be useless. I don't think any wallet fuzz target found a real issue yet?

I think we found a real issue with the coin selection target after the rework. But yes, it would be the only one.

> Coverage is nice, but if the fuzz test never finds any real user-facing issues, it will be useless. I don't think any wallet fuzz target found a real issue yet? Obviously coverage is the first step toward adding regression fuzz tests, so here are some ideas:
> 
> * [fuzz: Add regression test for wallet crash #23444](https://github.com/bitcoin/bitcoin/pull/23444) tried to add a regression fuzz test, but it was picked up as part of [fuzz: Faster wallet_notifications target #28933](https://github.com/bitcoin/bitcoin/pull/28933), and I couldn't reproduce the regression crash by re-introducing it.
> * [RPC: Fix fund transaction crash when at 0-value, 0-fee #27271](https://github.com/bitcoin/bitcoin/pull/27271) would be another idea to check
> * Something else?

I'm working on a target to cover and reproduce https://github.com/bitcoin/bitcoin/pull/27271.

**Comment by brunoerg** [comment]
Just added https://github.com/bitcoin/bitcoin/pull/29936 to the list. It's a regression to #27271.

**Comment by brunoerg** [comment]
Added https://github.com/bitcoin/bitcoin/pull/30134 to the list for review. It adds more coverage for `ScriptPubKeyMan`.

**Comment by kevkevinpal** [comment]
I started to take a look at the [Wallet RPC](https://github.com/bitcoin/bitcoin/issues/30458) issue, I'm still fairly new to fuzz testing so it might take longer but I am working off of [this branch](https://github.com/kevkevinpal/bitcoin/tree/fuzzwalletrpc) if you would like to track my progress.

**Comment by kevkevinpal** [comment]
I was able to get the coverage to Lines: %32 and functions %50

I think I just need to run the fuzzer for longer to get better coverage but I can do more testing and also cleanup my branch. If you would like the qa-assets for `wallet-rpc` please let me know.

![Screenshot 2024-07-30 at 10 42 26 AM](https://github.com/user-attachments/assets/7be52878-fb85-4237-8ade-f8fc896c8060)

**Comment by murchandamus** [comment]
Given that the first segment of your seeds need to correspond to an RPC command, a dictionary might help with bootstrapping.

**Comment by brunoerg** [comment]
Removed #30570 since it's closed.

**Comment by brunoerg** [comment]
Not sure about performance issues, but a fuzz target to cover https://github.com/bitcoin/bitcoin/issues/31474 would be great?

**Comment by brunoerg** [comment]
> Not sure about performance issues, but a fuzz target to cover [#31474](https://github.com/bitcoin/bitcoin/issues/31474) would be great?

I'm working on it.

**Comment by brunoerg** [comment]
`wallet_create_transaction` and `scriptpubkeyman` are two targets that I'm taking a look to try to speed them up. I'm getting less than 10 exec/s for both of them on my personal server which is bad. Just added to the "Nice to have" section the "Speed up current targets".

**Comment by brunoerg** [comment]
Just added https://github.com/bitcoin/bitcoin/pull/33916 to the review list. This PR adds a fuzz target for the `TransactionCanBeBumped` function from `feebumper`.
