### ISSUE TITLE
Cluster mempool tracking issue

### ISSUE THREAD

**Issue by sipa** [bitcoin/bitcoin#30289]
Plan:
* Lowest level: generic utilities:
  * [x] [#29242 FeeFrac type](https://github.com/bitcoin/bitcoin/pull/29242)
    * [x] [#30535 Add FeeFrac::EvaluateFee](https://github.com/bitcoin/bitcoin/pull/30535)
      * [x] [#32240 Fix integer overflow in FeeFrac fuzz test](https://github.com/bitcoin/bitcoin/pull/32240)
      * [x] [#32300 Fix different overflow in FeeFrac fuzz test](https://github.com/bitcoin/bitcoin/pull/32300)
  * [x] [#30160 BitSet type](https://github.com/bitcoin/bitcoin/pull/30160)
  * [x] [#30161 VecDeque type](https://github.com/bitcoin/bitcoin/pull/30161)
* Low level: operations on `DepGraph` type (dependencies/linearizations for a single cluster)
  * [x] [#30126 Base linearization algorithm](https://github.com/bitcoin/bitcoin/pull/30126)
    * [x] [#30605 Split tests from tests-of-tests](https://github.com/bitcoin/bitcoin/pull/30605)
    * [x] [#30857 Extend `DepGraph` functionality](https://github.com/bitcoin/bitcoin/pull/30857)
  * [x] [#30285 Merging and postprocessing of linearizations](https://github.com/bitcoin/bitcoin/pull/30285)
  * [x] [#30286 Optimized candidate search](https://github.com/bitcoin/bitcoin/pull/30286)
  * [x] [#32545 Replace linearization with SFL](https://github.com/bitcoin/bitcoin/pull/32545)
    * [x] [#34259 SFL chunk minimization](https://github.com/bitcoin/bitcoin/pull/34259)
  * [x] [#34023 SFL optimizations](https://github.com/bitcoin/bitcoin/pull/34023)
  * [x] [#34616 SFL cost model](https://github.com/bitcoin/bitcoin/pull/34616)
    * ~~[#34138 Old version](https://github.com/bitcoin/bitcoin/pull/34138)~~
* Intermediate level: operations on `TxGraph` type (dependencies/linearizations for the entire mempool)
  * [x] [#31363 TxGraph basics](https://github.com/bitcoin/bitcoin/pull/31363)
    * [x] [#32151 TxGraph basics follow-up](https://github.com/bitcoin/bitcoin/pull/32151)
    * [x] [#32177 TxGraph increase fuzz coverage](https://github.com/bitcoin/bitcoin/pull/32177)
    * [x] [#32191 Make TxGraph fuzzing more deterministic](https://github.com/bitcoin/bitcoin/pull/32191)
    * [x] [#33354 Use enum Level instead of bool main_only](https://github.com/bitcoin/bitcoin/pull/33354)
    * [x] [#33862 Drop support for `TxGraph::Ref` move assignment](https://github.com/bitcoin/bitcoin/pull/33862)
    * ~~[#33335 Randomize order of transactions](https://github.com/bitcoin/bitcoin/pull/33335)~~
    * [x] [#34257 Deterministic order of transactions](https://github.com/bitcoin/bitcoin/pull/34257)
  * [x] [#31444 TxGraph mining/eviction](https://github.com/bitcoin/bitcoin/pull/31444)
    * [x] [#33469 Use `std::unordered_set` for skipped clusters](https://github.com/bitcoin/bitcoin/pull/33469)
  * [x] [#31553 TxGraph reorgs](https://github.com/bitcoin/bitcoin/pull/31553)
  * [x] [#32263 TxGraph work controls](https://github.com/bitcoin/bitcoin/pull/32263)
  * [x] [#33157 TxGraph memory usage](https://github.com/bitcoin/bitcoin/pull/33157)
  * [x] [#34085 TxGraph exploiting SFL better](https://github.com/bitcoin/bitcoin/pull/34085)
* High level: changes to mempool/validation/RPC
  * [x] [#31122 Changesets for mempool](https://github.com/bitcoin/bitcoin/pull/31122)
  * [x] [#33629 Cluster mempool implementation](https://github.com/bitcoin/bitcoin/pull/33629)
    * ~~[#28676 Old version](https://github.com/bitcoin/bitcoin/pull/28676)~~
  * [x] [#33591 Cluster mempool optimizations and cleanups](https://github.com/bitcoin/bitcoin/pull/33591)
  * [x] [#34384 Remove epoch-based graph traversal](https://github.com/bitcoin/bitcoin/pull/34384)
  * [x] [#34615 Report mempool optimality](https://github.com/bitcoin/bitcoin/pull/34615)
---

Ideas for future follow-ups:
* Clean up the comparison operators of `FeeFrac`, especially the `operator<<` and `operator>>`: https://github.com/bitcoin/bitcoin/pull/34257#discussion_r2780475893
* Support registering a weight limit, and have txgraph track lower/upper bound for how much fees can be gathered within that size. With callbacks when it changes, waiting block template clients can be notified perhaps.

**Comment by summraznboi** [comment]
Wow, no ancestor/descendant limit would be great for unblocking UX hurdles in creating transactions! (Commenting to watch, also curious how someone like myself could help out here).

**Comment by sipa** [comment]
I declare victory!

Closing, though there are some follow-ups still interesting here.
