### ISSUE TITLE
Improving Fee estimation tracking issue

### ISSUE THREAD

**Issue by ismaelsadeeq** [bitcoin/bitcoin#30392]
This is a tracking issue for an effort to improve fee estimation on Bitcoin Core.

For the conceptual motivation behind this work, see  issue #27995 and  the previous discussion on Delving Bitcoin: [Mempool-Based Fee Estimation on Bitcoin Core](https://delvingbitcoin.org/t/mempool-based-fee-estimation-on-bitcoin-core/703/13), 

What to Review

- #30391
- #30275

Roadmap

- [ ] #30391
- [ ] Add Fee estimator Module / Mempool forecaster and unit tests
- [ ] Create `estimatefee` rpc and functional test
- [ ] Add fee estimation traces
- [ ] Add feature to the wallet

Complete Feature

- #30157

`BlockPolicyEstimator` improvements PR's

- #30079
- #30275:
  - [Delving Bitcoin analysis](https://delvingbitcoin.org/t/bitcoind-policy-estimator-modes-analysis/964/1)

Previous Refactors

- [x] #28368
- [x] #29013

Future Plans after [Cluster mempool project](https://github.com/bitcoin/bitcoin/issues/30289)

- Add sanity checks to ensure it is safe to use mempool-based fee estimation without falling back to `BlockPolicyEstimator` using ideas from [#27995](https://github.com/bitcoin/bitcoin/issues/27995)
- Make `BlockPolicyEstimator` package-aware: [Delving Bitcoin post](https://delvingbitcoin.org/t/package-aware-fee-estimator-post-cluster-mempool/312/10)
- Use heuristics from the mempool to target a higher/lower percentile in mempool forecaster

**Comment by ismaelsadeeq** [comment]
This issue was opened to track the effort to improve the Bitcoin core fee estimator. This comment will provide information on the status of this project and some key ideas on how to achieve this.

**Completed Tasks so far:**
- **Enabled asynchronous block policy fee estimator updates**: By making it a client of the validation interface.

- **Empirical data analysis**: To determine which forecasting strategy provides the most accurate estimates while withstanding common attack vectors.
- Developed a **rough model of the fee estimator architecture**: This model will enable adding more fee estimation strategies in the future.

- Ideas on how **policy estimator will improve accuracy post-cluster mempool**: By tracking chunks instead of individual transactions.

- **Brainstorm sanity checks for the fee estimator algorithms**: These checks ensure more robust estimates and help avoid common pitfalls when analyzing mempool data.

**Current Status:**

We have a rough implementation of the fee estimator that attempts to integrate these improvements. However, two things have not yet been implemented:

1. **Sanity checks**: Pending because the cluster mempool is still a work in progress. I have a WIP branch rebased on the cluster mempool to address this.
2. **Package-aware block policy fee estimator**: Also on hold for the same reason, awaiting the completion of the cluster mempool.

The fee estimator is currently a member of the node context exposed through the chain interfaces for the wallet and through node rpc's. 

The improvement above will require it to access both the mempool and the chainstate for building block templates.

I came across a suggestion that proposes:

https://github.com/bitcoin/bitcoin/blob/9f45062b9b0625cf4c714e2edbc7b6477164aaa9/src/interfaces/chain.h#L121-L123

This implies the need to create a fee estimation interface that would subscribe to chain interface notification events and expose its methods through the new fee interfaces.

IIUC the comment above hints towards having a separate fee estimation process in the future, allowing it to communicate with other interfaces through IPC?


This can be achieved by: 

1. **Decouple the notification handler from the chain interfaces** so that the fee estimator does not have to interact directly with the chain interfaces. It should only grab validation signals from the node interfaces and subscribe to the relevant events.
2. Creating an interface for fee estimation, which will instantiate the new fee estimator class and expose some methods for clients.
3. Update `createNewBlock` method in mining interface to return the vector of packages and fees in the the created block, and allow skipping some transactions when constructing the block template.

4. **Bitcoin node** will instantiate the fee interface by passing node and mining interfaces to it.

5. The **wallet interface** should also access the fee interface when it is being instantiated.

Once we have a multi-process architecture, the fee estimator can run in its process and communicate with other components through IPC.

cc @willcl-ark @josibake @glozow 

> Because I believe you are interesting in this project

cc cc @ryanofsky @TheCharlatan 

> Because I believe you are working on multiprocess and kernel project

> Feedback from other contributors is also welcomed and will be appreciated.

**Comment by jonatack** [comment]
> Create estimatefee RPC

Four years ago I was beginning to implement the roadmap as described in https://github.com/bitcoin/bitcoin/pull/20484#issuecomment-734786305, beginning with a `setfeerate` RPC in https://github.com/bitcoin/bitcoin/pull/20391 and a planned `estimatefeerate` RPC, both using sat/vB units. Was considering picking these up again. Presumably orthogonal, apart from coordinating on the RPC naming.

**Comment by remyers** [comment]
Concept ACK for improving fee estimation and this approach looks good. While reviwing data from [txstats](https://txstats.com/d/000000011/fee-estimation?orgId=1) in the context of optimizing how Eclair manages its utxo set I noticed the large variation between `estimatesmartfee` and, for example, mempool.space fee estimation. Eclair uses `estimatesmartfee` and recently changed from the (previous) default to `economical`. Any improvements to fee estimation in bitcoind will directly help to reduce costs for Eclair node operators.

**Comment by ismaelsadeeq** [comment]
> I'm not sure. Point 3 and the rationales in [#20484 (comment)](https://github.com/bitcoin/bitcoin/pull/20484#issuecomment-734786305) suggest a possibly safer way (perhaps you have a workaround in mind I'm overlooking).

You are right! I opened an issue for this #31088

**Comment by ismaelsadeeq** [comment]
> While reviwing data from [txstats](https://txstats.com/d/000000011/fee-estimation?orgId=1) in the context of optimizing how Eclair manages its utxo set I noticed the large variation between estimatesmartfee and, for example, mempool.space fee estimation.

Also see https://github.com/bitcoin/bitcoin/pull/30157#issuecomment-2128952313

>  Eclair uses `estimatesmartfee` and recently changed from the (previous) default to economical

Bitcoin Core 28.0 also updated its default to `economical`, so eclair users just need to update the node, and it should reflect the change.

**Comment by jsarenik** [comment]
Just few related notes, a compilation from what I have seen so far. HTH, may be biased and YMMV:

Yes, getting a transaction into a block (confirmed) is a future event so on all my nodes I do `ln -nsf /dev/null ~/.bitcoin/fee_estimates.dat` and never call the RPCs guessing "smart fee estimation" from historical values.

Setting a rational initial fee allows for simple (if not m-of-n multisig where `n>=m>1`) RBF replacements to increment the fee just by subtracting the `vsize` sats from one (or more, combined) output(s). See for example the RBF dance [on mempool.space/signet](https://mempool.space/signet/address/tb1p4tp4l6glyr2gs94neqcpr5gha7344nfyznfkc8szkreflscsdkgqsdent4) on the Alt Signet Faucet's main taproot address.

In case of `sat/vB` units I would suggest at least three decimal places. Works in Blockstream Green Wallet. See [a current example](https://mempool.space/signet/tx/2f7851901e8e194716f6c8fa662d545a0274b972c94755b24a50eca121dfbf67) on mempool.space, whereas the fee-rate used was `1.001` and child (fee-rate 20) does CPFP. Further I would suggest to use the transaction `weight` rather than `vsize`. The computation would look like `((weight*fee_rate)+3)/4` which is the same way how to get the `vsize` but once multiplying by the `fee_rate` (be it decimal or in `sat/kvB`) the results may differ.

Computaion of the top-left located "rational fee-rate" at [Anyone's Display](https://display.anyone.eu.org/price.html) is currently done by dividing the `total_fee` by number of blocks in the mempool. Try this shell-script to get the current mempool-sensitive value:

```sh
#!/bin/sh

eval $(bitcoin-cli getmempoolinfo \
  |  tr -d ', ".' | tr : = \
  | sed 's/=0\+/=/;1,2d;$d')
blocks=$((($bytes+999999)/1000000))
rfr=$(( ($total_fee+999)/1000/$blocks ))

# Exceptions:
#  1. if the computed value is below 1001
#    set it to 1001
test $rfr -lt 1001 && rfr=1001
# 2. if there is only one block in the mempool
#    set the value to 1000
test $blocks -eq 1 && rfr=1000

echo $rfr
```

Copying and pasting the above into you favorite Terminal works and to keep things clean I suggest running `env -i PATH=$PATH HOME=$HOME sh` first.

**Comment by ismaelsadeeq** [comment]
Hmm, I am not sure whether this is a rational fee rate.

1.  It's also unclear what confirmation target this "rational fee rate" is aiming for. 
2. I see there is a case where you just 1000  blindly this is not rational at all, it may be that your mempool is sparse because you just started your node, and you only have 1 block worth of transactions.
3. The script you provided does not also check against the minimum relay fee rate. Hence you might provide a fee rate below that and your transaction might not even propagate to your peers.

But nice website, and thanks for looking into this!

**Comment by ismaelsadeeq** [comment]
Following some positive feedback from the recent in-person Core Dev meeting, a notable one is from @ajtowns who suggest exposing the data used for the mempool health check

I’ve made several improvements:  

Updating the design document to reflect recent improvements and is now shared on 
github gist for more review and feedback https://gist.github.com/ismaelsadeeq/bcfa6b1216eef10076665551d9885722)  

#### Updated the  Complete Feature Implementation  

**Mempool Health Check**:  
The node’s mempool is validated against miner mempools using a better approach I thought of recently.  

This can easily be achieved through listening to validation interface notifications:  
- `MempoolTransactionsRemovedForBlock`: Use notification data to computes the total weight of transactions removed after a new block.  
- `BlockConnected`: Use notification data to computes the actual block weight.  

- Tracking this over six blocks provides a reliable indicator of mempool sanity.  

This method is lightweight and aligns with the approach used by the current block policy estimator. (https://github.com/bitcoin/bitcoin/pull/28368

See Implementation https://github.com/bitcoin/bitcoin/pull/30157/commits/3e4f293ba3bc89f7a42b7c15179d466f83743730 

**Filtering Transactions Skewing Fee Estimates**:  
- Transactions that consistently fail to confirm despite being in the top mempool block template are now filtered out.  This prevents misleading fee rate estimates due to miner policy deviations.   While rare, such cases can occurr (e.g., Ocean Mining).  
- See Implementation: https://github.com/bitcoin/bitcoin/pull/30157/commits/a81d3bda9c74936bb020d655443b31d692b17eb2 

This is an example output (`estimatefee 1 true`)  on mainet running #30157
```
{
  "minrelayfee": 0.00001000,
  "low": 0.00002006,
  "high": 0.00002118,
  "forecaster": "Mempool Forecast",
  "stats": [
    "Tracked 6 most-recent blocks.",
   "Block height: 887420, 3.99909e+06WU txs were seen in the mempool, Block weight: 3.99575e+06 WU (100.08% from mempool).",
    "Block height: 887421, 3.92792e+06WU txs were seen in the mempool, Block weight: 3.99165e+06 WU (98.40% from mempool).",
    "Block height: 887422, 4.00331e+06WU txs were seen in the mempool, Block weight: 3.99194e+06 WU (100.28% from mempool).",
    "Block height: 887423, 3.995e+06WU txs were seen in the mempool, Block weight: 3.99189e+06 WU (100.08% from mempool).",
    "Block height: 887424, 3.99632e+06WU txs were seen in the mempool, Block weight: 3.9919e+06 WU (100.11% from mempool).",
    "Block height: 887425, 4.00402e+06WU txs were seen in the mempool, Block weight: 3.99197e+06 WU (100.30% from mempool).",
    "We suspect 3 txs filtered by miners",
    "02ebbd8ca9e05de5fa056031ef....; count 4"
  ]
}
```

cc @willcl-ark, @glozow @instagibbs @davidgumberg @ryanofsky

**Comment by naiyoma** [comment]
Currently, we have two RPCs for fee estimation.
This new method will also introduce another RPC. Why not reuse the existing ones, since that’s what users are already familiar with—assuming they expect them to always return the most accurate fee between `FeeRateForecasterManager` and `CBlockPolicyEstimator`?

**Comment by ismaelsadeeq** [comment]
Good suggestion, I've done that. thanks @naiyoma  see recent push in #30157

**Comment by ismaelsadeeq** [comment]
Closed in favour of another approach in #34075
