### ISSUE TITLE
Remove libevent as a dependency (HTTP / cli / torcontrol)

### ISSUE THREAD

**Issue by pinheadmz** [bitcoin/bitcoin#31194]
Next PRs for review:

- [x] https://github.com/bitcoin/bitcoin/pull/32408
- [x] https://github.com/bitcoin/bitcoin/pull/32862
- [x] https://github.com/bitcoin/bitcoin/pull/32747
- [x] https://github.com/bitcoin/bitcoin/pull/34242
- [x] https://github.com/bitcoin/bitcoin/pull/34158
- [x] https://github.com/bitcoin/bitcoin/pull/34905
- [ ] https://github.com/bitcoin/bitcoin/pull/34772
- [ ] https://github.com/bitcoin/bitcoin/pull/32061
- [ ] https://github.com/bitcoin/bitcoin/pull/34342

There is also a proof-of-concept branch including the above work as well as total removal of libevent from the build system:

- [ ] https://github.com/bitcoin/bitcoin/pull/34411

### UNIX domain sockets for JSON-RPC
- Old feature request: https://github.com/bitcoin/bitcoin/issues/5029
- UNIX sockets have been added to [ZMQ](https://github.com/bitcoin/bitcoin/pull/27679) and [Tor proxy](https://github.com/bitcoin/bitcoin/pull/27375) already 
- UNIX sockets with libevent [doesn't work](https://github.com/bitcoin/bitcoin/issues/5029#issuecomment-2203469108)
### Remove a dependency
- libevent hasn't had a release since 2020
- [libevent is currently looking for new maintainers](github.com/libevent/libevent/issues/1812), a bit of a red flag
- The [xz utils backdoor](https://en.wikipedia.org/wiki/XZ_Utils_backdoor) raised some concern among contributors in the [2024/04/18 IRC meeting](https://www.erisian.com.au/bitcoin-core-dev/log-2024-04-18.html#l-198)

## Current libevent usage in the project
See [this report](https://gist.github.com/fjahr/c0c339a4b5021ae815d5bcff42e9fc57) by @fjahr. A few of these have already been addressed, like https://github.com/bitcoin/bitcoin/pull/29904

**Comment by hebasto** [comment]
>    * libevent hasn't had a release since 2020

Moreover, the new non-released code breaks our fuzzing tests. See: https://github.com/bitcoin/bitcoin/issues/30096.

**Comment by fanquake** [comment]
> Moreover, the new non-released code breaks our fuzzing tests. See: https://github.com/bitcoin/bitcoin/issues/30096.

I'm not so sure that's relevant. I think the conclusion in that issue was that vcpkg should probably stop shipping unstable/unreleased code, and I don't think we care about fuzzing unreleased versions of dependencies. It's less suprising that code which is still in development / might have API or other breaking changes we haven't accounted for might not work correctly.

**Comment by vasild** [comment]
Concept ACK on removing libevent.

In addition to the motivation from the OP, I would add that libevent is non-intuitive and difficult to work with (at least for me, this could be subjective). It was related to a remote crash via RPC: https://github.com/bitcoin/bitcoin/pull/27468

**Comment by fjahr** [comment]
Concept ACK on removing libevent and replacing the HTTP server with our own code. FWIW, I have been working on the removal of libevent from torcontrol but I still see some errors that I need to debug. I hope I can open a PR soon.

**Comment by vasild** [comment]
> I have been working on the removal of libevent from torcontrol but I still see some errors that I need to debug. I hope I can open a PR soon.

:heart:

poke me for review

**Comment by Reliestaff** [comment]
Agree

**Comment by pinheadmz** [comment]
There is a Signal working group for this project as well if anyone wants in lemme know

**Comment by JeremyRubin** [comment]
approach ack on removing libevent and having it operate over unix socket -- http functionality / REST can be provided via a proxy server.

**Comment by pinheadmz** [comment]
I found another edge case in libevent regarding URI handling, it does not decode `%XX` characters before parsing.

This is in libevent's `evhttp_uri_parse()` which is called by Bitcoin's `GetQueryParameterFromUri()`

Example, the URI:
`/rest/endpoint/someresource.json%3Fp1%3Dv1%26p2%3D100%25`
 decodes to `/rest/endpoint/someresource.json?p1=v1&p2=100%`

It will be interpreted by libevent (and therefore bitcoin core, currently) as one long path with no query parameters. 

Both Python's `urlparse()` and JavaScript's `decodeURIComponent()` will decode the `%XX` characters before parsing and identify the query, with two parameters, as separate from the path

**Comment by pablomartin4btc** [comment]
I've checked that and I see where the problem is...

If you run the following it works correctly (using/ changing `src/test/httpserver_tests.cpp`):

```
    uri = "/rest/endpoint/someresource.json?p1=v1%20&p1=v2";
    BOOST_CHECK_EQUAL(GetQueryParameterFromUri(uri.c_str(), "p1").value(), "v1 ");
```
```
./build/src/test/test_bitcoin --log_level=all --run_test=httpserver_tests
...
./test/httpserver_tests.cpp(52): info: check GetQueryParameterFromUri(uri.c_str(), "p1").value() == "v1 " has passed
...
```

So `evhttp_uri_parse()` works as expected(?) as soon the "encoded" char is in the variable's value (e.g. the following won't work: "/rest/endpoint/someresource.json%3Fp1=v1%20&p1=v2").

For the case where the "encoded" chars are among the path, we'd need to run the `evhttp_uridecode()`:

```
    uri = "/rest/endpoint/someresource.json%3Fp1%3Dv1%26p2%3D100%2525";
    char *decoded_path = evhttp_uridecode(uri.c_str(), 0, NULL); // Use c_str() here
    BOOST_REQUIRE(decoded_path != nullptr); // Ensure decoding succeeded

    std::cout << "Decoded path: " << decoded_path << std::endl;

    // Test query parameter extraction
    BOOST_CHECK_EQUAL(GetQueryParameterFromUri(decoded_path, "p2").value(), "100%");

    free(decoded_path); // Don't forget to free the decoded string
```

But as you can see the "encoded" path should be  "`/rest/endpoint/someresource.json%3Fp1%3Dv1%26p2%3D100%2525`" otherwise the libevent parse will fail because as in your example the "`/rest/endpoint/someresource.json?p1=v1&p2=100%`" is invalid ([RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-2.1):A % character must always be followed by two valid hexadecimal digits (0–9, A–F, a–f) that represent a byte value in hexadecimal notation). `evhttp_uridecode()` doesn't check if the encoded char is within the path or in the variable's value so perhaps we need to handle this special use case somehow.

**Comment by pablomartin4btc** [comment]
btw ACK on dependencies removal.

**Comment by pinheadmz** [comment]
@pablomartin4btc thanks, I added this test to my branch:

```cpp

    // Multiple parameters, some characters encoded
    uri = "/rest/endpoint/someresource.json?p1=v1%20&p2=100%25";
    BOOST_CHECK_EQUAL(GetQueryParameterFromUri(uri.c_str(), "p1").value(), "v1 ");
    BOOST_CHECK_EQUAL(GetQueryParameterFromUri(uri.c_str(), "p2").value(), "100%");
```

You're totally right, libevent decodes `%XX` but only after it has parsed the URI. Meaning the special characters `?` `&` and `=` (probably also `#`) can't be encoded the way we're currently using libevent.

**Comment by fjahr** [comment]
Can add [#34158](https://github.com/bitcoin/bitcoin/pull/34158) to the list :)

**Comment by pinheadmz** [comment]
> Can add [#34158](https://github.com/bitcoin/bitcoin/pull/34158) to the list :)

added! awesome! will review.
