### ISSUE TITLE
TODO for release notes 0.13.0

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7678]
Post things here that need explicit mention in 0.13 release notes

I'd strongly prefer for pulls to just update `doc/release-notes.md` directly, but if they somehow slip by, mention them here.

Summary:

- [ ] New options:
  - [ ] `-maxtimeadjustment`:  #7573
  - [x] `-reindex-chainstate` ( Optimize reindex #7917 ) (done in #8465)
- [x] New RPC call: 
  - [x] `generatetoaddress`: #7671
  - [x] `importprunedfunds` `removeprunedfunds`: #7558
  - [x] `signmessagewithprivkey` (introduced in #7953) 
- [x] Removed RPC calls:
  - [x] `setgenerate` Removal of internal miner: #7663, #7507
- [x] Changed RPC calls
  - [x] Output of RPC call `getrawmempool` has changed sort order (#7840)
  - [x] `fundrawtransaction`: #7518 Add multiple options to fundrawtransaction
  - [x] `fundrawtransaction`: #7967/#8153 add feerate option to fundrawtransaction
- [x] ARM executables have been added in #8188: need to update the release notes, as well as possibly the release process #8233
- [x] disabled mempool command when remove NODE_BLOOM support
- [x]  End support for Windows XP and older #7681

**Comment by laanwj** [comment]
Removal of internal miner: #7663, #7507

**Comment by laanwj** [comment]
New RPC call: `generatetoaddress`: #7671

**Comment by laanwj** [comment]
- New RPC calls `importprunedfunds` `removeprunedfunds`: #7558
- New option `-maxtimeadjustment`:  #7573

**Comment by laanwj** [comment]
I've added the Python 3.4 dependency for the functional tests in 7df9224. In the extremely unlikely case that #7814 is not merged before the release, this notice should be removed.

**Comment by laanwj** [comment]
New RPC call: `signmessagewithprivkey` (introduced in #7953)

**Comment by sdaftuar** [comment]
Output of RPC call `getrawmempool` has changed sort order (#7840)

**Comment by MarcoFalke** [comment]
@laanwj Can you move those into OP and add the `[ ] item` syntax? (Makes it possible to mark stuff that is already done)

Also, `-reindex-chainstate` ( Optimize reindex #7917 ) should be mentioned.

**Comment by laanwj** [comment]
Fundrawtransaction additions:
- #7967/#8153 add feerate option to fundrawtransaction

> Can you move those into OP and add the [ ] item syntax? (Makes it possible to mark stuff that is already done)

Yes, makes sense

**Comment by laanwj** [comment]
ARM executables have been added in #8188: need to update the release notes, as well as possibly the release process

**Comment by jonasschnelli** [comment]
* disabled mempool command when remove NODE_BLOOM support.

**Comment by laanwj** [comment]
End support for Windows XP and older #7681

This was not solved in the 0.13 window up until now, and there is very little chance it will still be.

**Comment by laanwj** [comment]
Closing this - maxtimeadjustment did not get an explicit mention, but being such a specific/advanced option that may be for the better.
