### ISSUE TITLE
Add benchmarks to `bench_bitcoin`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7883]
A benchmarking framework was added 6 months ago in #6733, but there are still no (non-silly) benchmarks added to it.
Would be nice if someone added some benchmarks, so that it is easier to see that claimed performance improvements really are such. Some ideas (some easy, some more involved):
- [x] Script validation (done in #8873)
- [ ] CCoinsDBView caching
- [ ] Coins database
- [x] Mempool (done in #8873)
- [x] EncodeBase58 performance see #7656 (done in #8107)
- [x] Wallet: Coin selection see #7823 (done in #8873)
- [x] SHA256 throughput and other cryptographic hashes (done in #8039)
- [x] LockedMemoryPool random allocation/deallocation performance (when #8753 merged)

**Comment by laanwj** [comment]
#7934 adds a benchmark for rolling bloom filter (thanks @sipa).

**Comment by yurizhykin** [comment]
Are those benchmarks supposed to cover all use cases (for example, EncodeBase58 for char arrays and std::strings, as well as for private/public keys, pubkey/script hashes etc), or just one or two cases?

**Comment by gmaxwell** [comment]
@yurizhykin It should be whatever is "useful"... if we don't ever use something in a way where performance matters, it's less likely to be useful.

**Comment by yurizhykin** [comment]
@gmaxwell Ok, so I will select most used cases for each item from the list above, and adjust it based on comments for the PR, if any.

**Comment by laanwj** [comment]
Right, I just listed some examples, if you want to be thorough it makes sense to profile (using e.g. valgrind) first and see where the bottlenecks are during various modes and operations and RPC commands.
I for example never expected EncodeBase58 to be a bottleneck for anything but it turned out to be.

> (for example, EncodeBase58 for char arrays and std::strings, as well as for private/public keys, pubkey/script hashes etc)

I think you should benchmark at the level of abstraction of the function. EncodeBase58 for encoding strings would be enough in this case. Size the strings to be around the size of the typical data encoded.

**Comment by yurizhykin** [comment]
Great, it sound like a nice guideline, thanks.

**Comment by droark** [comment]
Hi. I'm happy to write some benchmarks. I could use a bit of guidance, though. Which of the remaining ideas is (arguably) the easiest to implement? I'm tempted to say script validation but I'm still getting to know the nuances of the code.

Thanks.

**Comment by yurizhykin** [comment]
@droark, I think you're right about script validation. Also, coin selection seems to be not that hard. I started working on profiling approach, but had my uni exams started, so currently just read the codebase myself.

**Comment by laanwj** [comment]
Wallet coin selection is probably the hardest, as you need a wider selection of scenarios, just testing the same one over and over isn't too useful. Generating random isn't useful either for measurements. Maybe they could be deterministically generated. Or maybe just hand-pick a few representative ones.

The CCoinsView/CCoinsViewDB ones aren't too difficult. It's easy to create a temporary in-memory database (some other tests do this) and get and put values into it. Some database benchmarks could be very straightforward. Replicating the actual usage patterns of the client is hard though, many times micro-benchmarks of the database showed completely different characteristics than e.g. reindex timings. But that's not a requirement of every benchmark.

Basic mempool benchmarks shouldn't be too hard either. Just keep pushing transactions into it and see what e.g. the performance of eviction is.

Script validation is also quite straightforward.

**Comment by onurakdemir** [comment]
Hi,

Can you point me a bench that I can work on please? It is better if it is hard:)

**Comment by laanwj** [comment]
I think all the low-hanging fruit here is covered, it's unclear to me whether a benchmark of database things would make much sense in this context (how to make a micro-benchmark that even remotely reflects the real workload), so I'm closing this issue.
