### ISSUE TITLE
Remaining instances of ENABLE_WALLET in `libbitcoin_server.a`

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#7965]
We've been quite successful in eliminating these lately (#7905, #7691). 

It would be nice to disentangle the wallet and non-wallet initialization completely so that init.cpp no longer depends on the wallet (and thus, `libbitcoin_server.a` no longer depends on `libbitcoin_wallet.a` - the other way is fine, a circular dependency is not).

Ignoring the GUI for now (which still needs some work in this direction), the following are left:
- `init.cpp`: these are mostly self-contained and short. (#10762)
  - [x] print BerkeleyDB version should probably be moved to ~~`CWallet::InitLoadWallet`~~ `CWallet::Verify` (fixed in #8036).
  - [x] wallet-specfic option interaction (`-walletbroadcast`, `-prune`+`-rescan`) should move to wallet module (possibly a new call that can be called in addition to `InitParameterInteraction()`)
  - [x] printing setKeyPool size etc should probably be moved to `CWallet::InitLoadWallet`.
  - [x] wallet initialization/verify/shutdown - maybe this could be replaced by a general registration system for initialization/interrupt/shutdown functions, called as signals in the appropriate places. The same could be used by other modules
  - [x] `-disablewallet` could result in the wallet not being registered at all, and that can all be handled from outside init.
- RPC still has some calls that vary depending on wallet support. We should split these up. This is the more annoying part as it will involve API changes. No non-wallet RPC call should make an assumption about "a wallet".
  - `rpcmisc.cpp`
    - [x] `getinfo` - this call is already on the list to be deprecated for a long time (#10838)
    - [x] `validateaddress` - should be split up into an utility-only `validateaddress` and a wallet-specific call `getaddressinfo` (name open for discussion) (#10583)
    - [x] `createmultisig` - same. `createmultisig` and `walletcreatemultisig` or so (#11415)
  - [x] `rpcblockchain.cpp`
    - [x] `signrawtransaction` - should be split into an utility-only `signrawtransaction` and a wallet-specific call `walletsignrawtransaction` (#10579)
  - [x] remove deprecated `validateaddress` and `signrawtransaction` wallet dependency completely (#12490)
- [x] Mining: no `ENABLE_WALLET` but an implicit assumption and a circuitous registration system. The `generate` call should be a wallet-specific call, whereas `generatetoaddress` is core. See discussion in #6481. (done in #10683).
- [x] in `httprpc.cpp`, there are #ifdef ENABLE_WALLETs protecting registration/unregistration of the wallet endpoint. These can trivially be replaced with calls into the WalletInitInterface.
- [ ] in `interfaces/node.cpp`, #ifdef ENABLE_WALLET protects the calls to getWallets(). This can easily be replaced by calls into a wallet manager/dummy wallet manager.

The first phase would be to introduce the new (wallet-only) methods, then a release later remove wallet functionality from the core-only calls.

**Comment by laanwj** [comment]
I think it may be nice to implement `getinfo` (or something similar) client-side in `bitcoin-cli`. For users of the command line it has some value as a status overview of the entire node+wallet, and it's simple enough to gather the info from that verious `getXXXinfo` calls and return it in one screen.

**Comment by MarcoFalke** [comment]
The `InitLoadWallet` thing can be marked as "done"

**Comment by MarcoFalke** [comment]
I have modified the OP to reflect the current status based on the pulls that point to this issue.

**Comment by laanwj** [comment]
Thanks!

**Comment by laanwj** [comment]
> `signrawtransaction` - should be split into an utility-only signrawtransaction and a wallet-specific call walletsignrawtransaction.

Related: #4844

**Comment by luke-jr** [comment]
IMO utility-only signrawtransaction belongs in bitcoin-tx, and leave the RPC as wallet-specific.

**Comment by laanwj** [comment]
I tend to agree, although deprecating utility-only RPCs is a bit of an orthogonal issue. The main practical problem there is that bitcoin-tx is not a library, and doesn't have language bindings, whereas RPC does. Calling out to a program is not always acceptable. I **suppose** people are using `signrawtransaction` when they don't have a library for their programming language to provide that functionality locally. And it's preferable to ask bitcoind than use a badly hand-rolled one, imagine how badly ECDSA signing could be implemented in PHP...

So while I agree on the long-term vision there, I think on the short run it may make sense to split the call instead.

**Comment by luke-jr** [comment]
That's a good point. In that case, perhaps make the utility version be the awkward name, since the long-term plan is to move it out?

**Comment by laanwj** [comment]
Fine with me, I don't want to get into bikeshedding here. What is your proposal regarding naming?

**Comment by achow101** [comment]
#10579 does the `signrawtransaction` part of this

**Comment by achow101** [comment]
I think this should be moved to the future milestone as all that primarily remains are RPC calls which all will require deprecation for a few versions first

**Comment by jnewbery** [comment]
Please update the PR info to reference the relevant PRs:

- #10762 removes wallet dependencies from init.cpp
- #10838 removes `getinfo`
- #10583 splits `validateaddress` into wallet/non-wallet parts
- #10579 splits `signrawtransaction` into wallet/non-wallet parts

`createmultisig` is the only remaining part that we don't have a PR for.

I also think we should label this 0.16. Should be easily achievable.

**Comment by laanwj** [comment]
@jnewbery @achow101 Thanks, added

**Comment by jnewbery** [comment]
#11415 has been merged. Can someone strike it from the list in this PR?

**Comment by MarcoFalke** [comment]
Done

**Comment by jnewbery** [comment]
#10579 has been merged. Please strike from the list.

Also add #12490, which actually removes the wallet dependencies from rpc.

**Comment by laanwj** [comment]
@jnewbery Done

**Comment by laanwj** [comment]
Updated for #10762. We're so close now.

This is the only open item according to the OP:

> remove deprecated validateaddress and signrawtransaction wallet dependency completely (#12490)

**Comment by laanwj** [comment]
> There are a few other #ifdef ENABLE_WALLETs introduced since this issue was opened:

I noticed. Agree (1) is not really a problem as it doesn't introduce a dependency. Just the theoretical architectural concern that libbitcoin_server.a could be built independently of --enable/disable-wallet. But given the monolithic build I don't think that's a short term priority, certainly not the reason I created this issue :)

But yes, the other two need to go.

**Comment by MarcoFalke** [comment]
Updated milestone to 0.18.0 accordingly.

**Comment by jnewbery** [comment]
I've opened #14168 to remove the final instances of ENABLE_WALLET in libbitcoin_server.

> in interfaces/node.cpp, #ifdef ENABLE_WALLET protects the calls to getWallets(). This can easily be replaced by calls into a wallet manager/dummy wallet manager.

This is actually in libbitcoin_util, so I think it can be removed from this issue.

**Comment by jnewbery** [comment]
#14168 is merged.

The final instance of `#ifdef ENABLE_WALLET` is actually in libbitcoin_util, so I think we're done here.

@laanwj - do you agree? Should we close this issue, or keep it open to track removing the `#ifdef ENABLE_WALLET` from libbitcoin_util?

**Comment by laanwj** [comment]
@jnewbery The issue mentions only `libbitcoin_server.a` but I think that is because I assumed the only instances of `ENABLE_WALLET` would be in the server and GUI, not utilities that are linked into the `-cli` and `-tx` as well. That's kind of surprising.

I'm surprised, I don't think `interfaces/node.cpp` should be in `libutil` in the first place? What needs it, outside of bitcoin-qt and bitcoind?

**Comment by laanwj** [comment]
The last step here was done in #14208, which was merged shortly ago. This means that this long-running issue can finally be closed. Yay!
