### ISSUE TITLE
avoid shadowing vars, and enable -Wshadow

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#8105]
I haven't looked into a fix for this, but it should be easy to implement and hopefully uncontroversial.

Relavant bug: https://github.com/bitcoin/bitcoin/pull/8102#issuecomment-221934374

TODO:
- [x] `univalue` shadowing fix (merged, synced to our tree )
- [x] `serialize.h` and `nVersion`, `nType` collisions (~~#8468~~ #9039 )
- [x] `LOCK` inside `LOCK`shadowing (using `__COUNTER__` for `LOCK` macro) (#8472)
- [x] other misc source fixes
- [x] enabling `-Wshadow` (#8794)
- [x] document `-Wshadow` and add developer notes about it (#8794)
- [ ] `leveldb` shadowing fix ? (https://github.com/google/leveldb/pull/378, but fixed by other changes there.)
- [ ] GCC Set #8808

**Comment by theuni** [comment]
@MarcoFalke We're guilty of this all over the place (serialization in particular), so while it would be simple, the actual change-set would probably be rather large.

I'm all for it though, this is a long-standing annoyance of mine.

**Comment by paveljanik** [comment]
I remember I tried it already and failed. These `nVersion` variables were nightmare ;-)

**Comment by sipa** [comment]
Many of the nVersion variables are totally unnecessary.

**Comment by paveljanik** [comment]
I'll dig the work/redo the configure stuff.

**Comment by MarcoFalke** [comment]
Even though it may not be possible to fix all at once, it is good to keep this in mind for new code or whenever code is touched/moved due to other reasons.

**Comment by paveljanik** [comment]
Global tasks to be solved:

- [ ] `univalue` shadowing fix (https://github.com/jgarzik/univalue/pull/23)
- [ ] `serialize.h` and `nVersion`, `nType` collisions
- [ ] `LOCK` inside `LOCK`shadowing
- [ ] other misc source fixes
- [ ] enabling `-Wshadow`

**Comment by MarcoFalke** [comment]
It is good to see progress on this, but it may be worth to wait until segwit (and maybe p2p-refactor) is merged to avoid unnecessary code-conflicts.

**Comment by paveljanik** [comment]
Agreed, I'll wait with submitting "destructive" changes. Working on it in private tree now.

**Comment by paveljanik** [comment]
FYI: I was able to fix serialization issues. I'll wait for #8109, #8163, #8191 and #8449 merge to get clean tree. Please help ACK them. Thank you!

**Comment by paveljanik** [comment]
Current status:

3 PRs opened.

Remaining: complete QT (33 files, 200 changes, will be done later), ~20 other files outside of qt. Approx. 5 changes call for more review and will be PRed separately.

**Comment by MarcoFalke** [comment]
Could you submit the changes required for qt and then enable the warning, so we don't have new instances popping up accidentally?

**Comment by paveljanik** [comment]
I do not have them in the ready-to-merge quality yet.

Enabling the `-Wshadow` now is a no go from me, because there are approx. 500 warnings in `qt` now...

**Comment by paveljanik** [comment]
I pushed my changes in qt here: https://github.com/bitcoin/bitcoin/commit/f9d00d7e624a6760a099ca61caca25d7982844d1

**Comment by MarcoFalke** [comment]
> I haven't double-checked them all yet.

As long as the binaries match, there is not much to lose. Also, for qt it should be easier to get in.

**Comment by laanwj** [comment]
Yes, Qt will be much easier to merge. If that's the blocker to enabling the warnings by default, let's just get it over with.

**Comment by paveljanik** [comment]
Current status: with #8468, #8655, #8658, #8794 and upstreamed-univalue and upstream-leveldb fix, there are no Wshadow warnings on OS X.

**Comment by paveljanik** [comment]
I'll now try to target some gcc version, so we are ready to enable `-Wshadow` by default and people on Linux boxes are not flowed by warnings...

**Comment by fanquake** [comment]
We still have at-least #8808 to be merged before this can be closed. Have updated the original issue with remaining TODOs.

**Comment by laanwj** [comment]
I don't think enabling WShadow by default is worth doing anymore.

This is very much dependent on the compiler, and some compilers may be overly struct. When googling around about Wshadow there are tons of complaints about it being too strict for some compilers, or even having false positives. Enabling this by default for all compilers will result in an unending source of complaints.

I thought this was something that could be done quickly. It was not my intention to merge "remove WShadow warnings" for the large part of a year. The cure seems worse than the ailment in this particular instance.

**Comment by MarcoFalke** [comment]
Closing this then.

Though, I think if #8808 is the last step, we could give it a try once and revert when it turns out to create more noise than signal.

So lets move the final discussion/decision to #8808 and close this issue.

**Comment by paveljanik** [comment]
It makes no sense to close this, sorry.

The enable change was merged prematurely as I already said. #8808 was missing and thus gcc users could see some warnings. And gcc6 needs more but small changeset. I'll have it ready tomorrow (@gmaxwell already tested the change at http://tmp.janik.cz/q.diff).

**Comment by MarcoFalke** [comment]
I think it is fine if you just cherry-pick fd5654c into 8808, no need to open a separate pull or keep this issue open.

**Comment by paveljanik** [comment]
Just for the record: another `gcc`, another small update to univalue https://github.com/jgarzik/univalue/pull/34.
