### ISSUE TITLE
TODO for release notes 0.15.0

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#9889]
Whenever possible, please amend the `doc/release-notes.md` within the pull that introduces a new fancy feature or breaks compatibility.

If this is not possible, please mention the pull here, so it can be taken care of later:

* [x] RBF GUI (#9592, ...)
* [x] #9602: Remove coin age priority and free transactions
* [x] [wallet] Rescan abortability #10208 adds `abortrescan` RPC
* [x] leveldb 1.20 #10138
* [x] #9733 adds `getchaintxstats` RPC
* [x] #9966 adds `-persistmempool` option
* [x] #8952 adds query options to `listunspent` RPC
* [x] #10478 adds `bindaddr` address for peer connections to `getpeerinfo` 
* [x] #9740 makes `dumpwallet` return the full absolute path to the dumped wallet
* [x] #10400 adds `uptime` command
* [x] Move transaction combining from signrawtransaction to new RPC #10571
* [x]  Do not allow users to get keys from keypool without reserving them #10784 

<sub>Feel free to edit

The release notes are now edited on the wiki:

https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes

**Comment by MarcoFalke** [comment]
* [ ] RBF GUI (#9592, ...)
* [ ] #9602: Remove coin age priority and free transactions

**Comment by NicolasDorier** [comment]
https://github.com/bitcoin/bitcoin/pull/9728

**Comment by laanwj** [comment]
@NicolasDorier to be clear, this issue is to keep track of items that are already merged but need release notes updates

**Comment by laanwj** [comment]
[wallet] Rescan abortability #10208 adds `abortrescan` RPC

**Comment by jnewbery** [comment]
#10204 changes an RPC argument name. It's being backported to 0.14.1 - does it need 0.15 release notes as well, or do the 0.14.1 release notes cover it?

**Comment by laanwj** [comment]
[net] Allow disconnectnode RPC to be called with node id #10143 adds `nodeid` argument

> does it need 0.15 release notes as well, or do the 0.14.1 release notes cover it?

Things should only end up in one release notes at most: the first release that has them.

**Comment by laanwj** [comment]
- #9733 adds `getchaintxstats` RPC
- #9966 adds `-persistmempool` option

**Comment by laanwj** [comment]
- #8952 adds query options to `listunspent` RPC

**Comment by laanwj** [comment]
- #10478 adds `bindaddr` address for peer connections to `getpeerinfo`

**Comment by TheBlueMatt** [comment]
#10488 (and #10252) update the prioritizetransaction RPC API further after #9602, and the release notes for 9602 should include those changes as well.

**Comment by laanwj** [comment]
- #10400 adds `uptime` command

**Comment by TheBlueMatt** [comment]
Hopefully #10707 will make it, and will thus need release notes.

**Comment by laanwj** [comment]
Should add a release notes section about all the wonderful perf improvements in 0.15
- new and better per-utxo database format, non-atomic flushing
- tx validation caching (that's massive for performance at the tip)
- CRC instruction support in leveldb 1.20
(and more)

**Comment by jtimon** [comment]
What about something like "more progress reducing dependencies like boost after moving to c++11"?
I remember #10502 and #10193 , but IIRC more work has done in this regard, right?

**Comment by MarcoFalke** [comment]
Boost will stick to us for a few releases at least. So this is just
internal refactoring, irrelevant to release notes.

**Comment by laanwj** [comment]
> What about something like "more progress reducing dependencies like boost after moving to c++11"?
I remember #10502 and #10193 , but IIRC more work has done in this regard, right?

In contrast to performance improvements, which are a good selling point for a relesae, it doesn't seem an end-user would care about that.

After the dependency on boost completely goes away, sure, we should mention it for builders.

**Comment by TheBlueMatt** [comment]
#10784, if it makes it.

**Comment by TheBlueMatt** [comment]
#10571.

**Comment by MarcoFalke** [comment]
Due to request in yesterday's meeting, the release notes can now be edited on the wiki:

https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes

**Comment by jnewbery** [comment]
#10604 adds `listwallets` command

**Comment by jnewbery** [comment]
I've added the following to the wiki:

- multiwallet
- `-persistmempool`
- `abortrescan`
- `getchaintxstats`
- `listwallets`
- `uptime`
- `listunspent` has `query_options` argument
- `dumpwallet` returns path of dump file.
- `getpeerinfo` returns `addrbind`
- `disconnectnode` has `nodeid` argument
- `combinerawtransaction`
- `fundrawtransaction` no longer takes `reserveChangeKey`
- changes to `estimaterawfee`
- change `priorisetransaction` and `submitblock` argument names to `dummy`

Is one of the maintainers able to check the boxes in the Issue notes and strike through the individual comments for these items (so it's clear what is left to be done)?

**Comment by jnewbery** [comment]
Added a performance improvements section (https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#performance-improvements):
- per-TXO chainstate (#10195)
- script caching (#10192)
- leveldb v1.20 hardware accelerated CRC (#10138)
- SHA256 hardware acceleration (#10821)

@sipa suggested #9665 and #10249 as other performance wins, but I think they're quite difficult to quantify as x% IBD/validation gain, so I've left them out of the performance improvement section. They could perhaps be included elsewhere in the release notes.

**Comment by jnewbery** [comment]
Added release notes for:
- opt-in RBF in bitcoin-qt (#9592)
- fee bumper in bitcoin-qt (#9697)

here: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#replace-by-fee-control-in-the-gui

**Comment by jnewbery** [comment]
Added a section on 'Removal of Coin Age Priority' (#9602) here: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#removal-of-coin-age-priority.

I believe that completes Release Notes for everything that has been mentioned in this issue prior to this comment.

I think we still need release notes for:

- upgrade advice/downgrade warnings. @luke-jr is currently writing this
    - I'd like this to include a note saying direct upgrade from 0.7 and earlier is not supported (https://github.com/bitcoin/bitcoin/pull/9822#issuecomment-281678689)
- Various improvements to fee logic (perhaps @morcos can write this?)
- #10543 Change to `estimaterawfee` interface (probably in same section as https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#changes-to-the-estimatesmartfee-api)
- #10148 (Use non-atomic flushing with block replay)
- (Perhaps) #10557 (Make check to distinguish between orphan txs and old txs more efficient). It's an implementation detail so perhaps not worth including unless it's a big perf win.
- (Perhaps) #9665 (Use cached [compact] blocks to respond to getdata messages). It's an implementation detail and difficult to quantify what the gains are from this.
- (Perhaps) #10249 (Switch CCoinsMap from boost to std unordered_map). An implementation detail, but if we can quantify the perf win it should go in the *Performance Improvements* section.

**Comment by jonasschnelli** [comment]
GUI fee selection changed from slider to a dropdown supporting confirmations-targets up to 1008 https://github.com/bitcoin/bitcoin/pull/10769

**Comment by MarcoFalke** [comment]
Not sure if we need to mention the change from slider to dropdown. I think
this GUI change is pretty self-explanatory.

**Comment by jnewbery** [comment]
Thanks to whoever updated the issue notes with the current status (@MarcoFalke I assume). I see two items were added: *Move transaction combining from signrawtransaction to new RPC* and *Do not allow users to get keys from keypool without reserving them*. Those are both mentioned in https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#low-level-rpc-changes. Do you think they deserve their own sections?

**Comment by jnewbery** [comment]
Thanks @luke-jr for cleaning up my notes and adding the upgrade section. Your revision looks good. The only part of https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes/c8f33d3eafe9fe3da16f68a34dfaf7b0db85ed65 I'd disagree with is:

> (Clients should, however, use positional arguments for submitblock in order to be compatible with BIP 22.)

I don't think the release notes should dictate how users/clients access the RPCs. *submitblock* supports named arguments just like all other RPCs. Do you mind if we remove that part?

**Comment by jnewbery** [comment]
I've added the changes to `estimaterawfee`: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#changes-to-the-estimatesmartfee-and-estimaterawfee-apis. Ping @morcos for review.

**Comment by jamiewaltz** [comment]
Stop sending me emails please

**Comment by laanwj** [comment]
@jnewbery Wow, thanks for the release note updates!

@jamiewaltz Github provides an unsubscribe link in emails, as well as an "Unsubscribe" link when you go to the issue in question. Please use either ofthose. The only thing I can do is block you from the project completely, which is probably not what you want.

**Comment by jnewbery** [comment]
I've added a section on Fee Estimation Improvements: https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes#fee-estimation-improvements

Perhaps @morcos can review to make sure I've captured everything accurately.

**Comment by MarcoFalke** [comment]
Going to close this. Looks like everything has been addressed.

Otherwise, just head over to the [draft](https://github.com/bitcoin-core/bitcoin-devwiki/wiki/0.15.0-Release-notes-(draft)) and fix it.

**Comment by laanwj** [comment]
Seems continued in #11174 (not sure why not just reopening this one)
